IBM/openapi-validator

README.md

* Duplicate word on paragraph #140
* Plus minor formatting proposals

Typos on paragraph #38 & #51.

---

.releaserc
.travis.yml
CONTRIBUTING.md
README.md
package-lock.json
package.json
test/cli-validator/tests/optionHandling.js

Sets up `semantic-release` for the project.
- Installed `semantic-release` as a dependency
- Added the necessary tokens as environment variables in Travis
- Wrote a `.releaserc` that is essentially the same as in the Node SDK
- Added a deploy script to the `.travis.yml` file

Add semantic release

---

CHANGELOG.md

updating the changelog to include recent PRs

docs: retroactively update changelog with recent updates

---

README.md

This PR adds the CLA-Assistant badge to the README file.  The CLA-Assistant has (hopefully) been configured for this repo so that all PRs will ensure that the authors have signed the CLA.

Add CLA-Assistant badge

---

test/cli-validator/tests/expectedOutput.js
test/cli-validator/tests/optionHandling.js

changes to the test cases to accommodate for new configuration settings

addressing pr feedback

---

src/plugins/validation/2and3/semantic-validators/parameters-ibm.js
test/plugins/validation/2and3/parameters-ibm.js

More specific checks for parameters that will check specifically for parameter objects and should not complain to properties named parameters. Will also check for parameters in a top level for swagger 2 and for parameters in path items.

fix: more specific checks for parameter objects

---

test/plugins/validation/2and3/paths-ibm.js

Add tests for duplication path parameter rule.  These were supposed to be included in PR #112, but somehow "got lost".

test: Add tests for duplicate path parameter rule

---

README.md
package-lock.json
package.json
src/cli-validator/index.js
src/cli-validator/runValidator.js

This PR fixes package vulnerabilities reported by npm audit.  I also added a `--debug` command line argument to turn on printing of debug information.

Fix package vulnerabilities reported by npm audit

---

package-lock.json
package.json

This PR fixes issues reported by npm audit.  I used `npm audit fix` to update the dependencies then ran `npm test` to ensure nothing broke as a result.

Fix issues from npm audit

---

src/plugins/validation/2and3/semantic-validators/items-required-for-array-objects.js
src/plugins/validation/2and3/semantic-validators/operation-ids.js
src/plugins/validation/2and3/semantic-validators/schema-ibm.js
src/plugins/validation/oas3/semantic-validators/responses.js

This PR adds the rule name to the `addMessage` call for some cases that were missed in PR #222.

Specify rule name for all configurable rules

---

README.md

docs: add further justification for inline response schema warnings

---

src/plugins/validation/2and3/semantic-validators/walker-ibm.js
test/plugins/validation/2and3/walker-ibm.test.js

fix: allow null values in 'default' property

---

.releaserc
README.md

This changeset contains small changes to support the renaming of the `master` branch to `main`.

chore: main migration

---

src/cli-validator/utils/buildSwaggerObject.js

We do some validations on the "resolved spec" or the full API definition with all of its
references resolved into one large document. This takes multi-file specs into account and
resolves all references, even to other files. However, some validations are performed only
on the original spec as it provides some benefits, such as gathering all schemas without
worrying about duplicates. The problem with our current approach is that, if the spec is
split into multiple files, we only validate the entry file and none of the others.
This adds a quick step to "bundle" all of the files together into one "file" that only has
internal references. This way, the unresolved "js spec" will represent the entire definition.
Resolves #229

fix: bundle original spec to account for multi-file API definitions

---

package-lock.json

Purpose:
- npm identified many security vulnerabilities including some high-risk vulnerabilities, and we want to clean up our dependencies.
Changes:
- This PR updates the validator's dependencies to resolve these problems using a simple `npm audit fix`.
Result:

build: update validator dependencies

---

package-lock.json
package.json

Purpose:
updating globby package to fix [high vulnerably](https://github.com/advisories/GHSA-ww39-953v-wcq6).
Changes:
Updated globby package from 8 to latest (11.0.4)
Test:
Ran test to ensure the package works as expeceted
Docs:
Hope no docs are requires

fix: vulnerability fix updating package

---

src/plugins/validation/2and3/semantic-validators/operations-shared.js

Make it easier to disable `operation_id_case_convention`

---

.secrets.baseline
package-lock.json
src/spectral/rulesets/.defaultsForSpectral.yaml
test/spectral/tests/custom-rules/servers-variable-default-value.test.js

This PR brings the capability of checking whether
a server variable has a default value or not. If not,
then we are going to display warning.
The code snippet below will display warning.
```
servers:
- url: 'https://example.com'
description: 'A server which has variable without default value'
variables:
name:
default: ''
```

feat: server variables must have default value

---

package-lock.json

chore: fix vulnerable dependency

---

.travis.yml
package-lock.json
package.json

This PR removes the codecov uploader from the project due to security vulnerabilities associated with the uploader and codecov site.

build: remove codecov from project

---

packages/ruleset/src/functions/schema-description.js
packages/ruleset/test/schema-description.test.js

Previously, the schema-description rule did not consider a schema's
allOf/anyOf/oneOf list when checking to see if a schema has a description.
This commit fixes that.

fix(schema-description): consider descriptions within allOf/anyOf/oneOf

---

package-lock.json
packages/ruleset/src/collections/index.js
packages/ruleset/src/functions/index.js
packages/ruleset/src/functions/parameter-description.js
packages/ruleset/src/ibm-oas.js
packages/ruleset/src/rules/index.js
packages/ruleset/src/rules/parameter-description.js
packages/ruleset/test/array-of-arrays.test.js
packages/ruleset/test/description-mentions-json.test.js
packages/ruleset/test/discriminator.test.js
packages/ruleset/test/parameter-description.test.js
packages/ruleset/test/utils/root-document.js
packages/validator/src/.defaultsForValidator.js
packages/validator/src/plugins/validation/2and3/semantic-validators/parameters-ibm.js
packages/validator/test/cli-validator/tests/config-file-validator.test.js
packages/validator/test/cli-validator/tests/error-handling.test.js
packages/validator/test/plugins/validation/2and3/parameters-ibm.test.js

This commit converts the old no_parameter_description rule
to a new Spectral-style 'parameter-description' rule.

feat(parameter-description):  add new 'parameter-description' rule and remove old rule

---

docs/ibm-cloud-rules.md

This PR updates the docs/ibm-cloud-rules.md document to be clearer about our ruleset and how to customize rules within it.

docs: add content for customization steps [skip ci]

---

package-lock.json
package.json

This PR bumps a few dependencies to avoid security vulnerabilities.

build: bump dependencies to avoid vulnerabilities

---

.cra/.cveignore
.secrets.baseline
package-lock.json
package.json

Bumps our version of the @semantic-release/npm dependency to avoid vulnerabilities

build: bump npm version to avoid vulnerabilities

---

packages/ruleset/src/functions/index.js
packages/ruleset/src/rules/index.js
packages/ruleset/src/utils/index.js

With apologies for the conflicts, but is there anything wrong with this simplification?

refactor: simplify ruleset index files

---

package-lock.json

Bumps vm2 package to avoid vulnerability SNYK-JS-VM2-3018201

chore: bump vm2 to avoid vulnerability

---

.secrets.baseline
docs/ibm-cloud-rules.md
package-lock.json
packages/ruleset/src/collections/index.js
packages/ruleset/src/functions/inline-schema-rules.js
packages/ruleset/src/ibm-oas.js
packages/ruleset/src/rules/index.js
packages/ruleset/src/rules/inline-property-schema.js
packages/ruleset/src/utils/index.js
packages/ruleset/src/utils/is-empty-object-schema.js
packages/ruleset/test/description-mentions-json.test.js
packages/ruleset/test/inline-property-schema.test.js
packages/ruleset/test/is-empty-object-schema.test.js
packages/validator/test/cli-validator/mock-files/oas3/clean.yml

'inline-property-schema' validation rule.
It will look for and warn about any nested objects that are defined with an inline object schema.

feat(inline-property-schema): add new spectral-style rule

---

.releaserc
.travis.yml

This PR modifies the build so that we can build the executables AFTER semrel updates the package.json file so that they will contain the correct (new) release #.

fix: build executables with correct release

---

.travis.yml
README.md
packages/ruleset/package.json
packages/validator/package.json

This PR upgrades our min node version to v14.

feat: bump min node version to 14

---

Migration-Guide.md
README.md

Adds a migration guide for the new 1.0 validator.

docs: add new migration guide

---

README.md

This PR adds some docs related to the validator's use of loggers.

docs: add logging section to README.md

---

Migration-Guide.md

Updates to the migration guide.

docs: add rule list to migration guide

---

packages/ruleset/src/functions/required-property.js
packages/ruleset/test/required-property-missing.test.js

and add a test case to demonstrate gap

fix: edit logic to recursively account for nested composed schemas

---

.cra/.cveignore
.eslintrc.js
package-lock.json
package.json
packages/validator/package.json

This commit upgrades several dependencies, including the eslint version.  This was primarily done to avoid a vulnerability reported in the word-wrap package which is an indirect dependency. I also removed several unnecessary dependencies from package.json.

fix(build): avoid vulnerability reported in word-wrap dependency

---

README.md
package-lock.json
package.json
packages/validator/package.json
packages/validator/test/cli-validator/tests/option-handling.test.js
packages/validator/test/test-utils/get-captured-text.js
packages/validator/test/test-utils/index.js
packages/validator/test/test-utils/strip-ansi.js

This PR uses the "overrides" field in package.json to override a couple of transitive dependencies to avoid vulnerabilities in word-wrap and semver.

build: avoid semver and word-wrap vulnerabilities

---

package-lock.json
package.json

Fixes: #607
This PR bumps our versions of a few dependencies to avoid the critical vulnerability reported in the "vm2" transitive dependency.

fix: override proxy-agent to avoid vulnerabilities

---

.secrets.baseline

build: fix detect-secrets issue

---

.secrets.baseline
docs/ibm-cloud-rules.md
packages/ruleset/src/functions/api-symmetry.js
packages/ruleset/src/functions/index.js
packages/ruleset/src/functions/schema-naming-convention.js
packages/ruleset/src/ibm-oas.js
packages/ruleset/src/rules/api-symmetry.js
packages/ruleset/src/rules/index.js
packages/ruleset/src/utils/compute-refs-at-paths.js
packages/ruleset/src/utils/get-resource-oriented-paths.js
packages/ruleset/src/utils/get-schema-name-at-path.js
packages/ruleset/src/utils/index.js
packages/ruleset/src/utils/schema-finding-utils.js
packages/ruleset/test/api-symmetry.test.js
packages/ruleset/test/utils/root-document.js

Ensures that Summary, Prototype, and Patch schemas are proper graph fragments of the canonical schema they are variants of.

feat(new-rule): ibm-api-symmetry

---

.cra/.cveignore
package-lock.json

Add false-positive for CVE-2024-24828, and bump our version of babel to address a potential vulnerability.

build: add false-positive for CVE-2024-24828

---

docs/ibm-cloud-rules.md
packages/validator/src/cli-validator/run-validator.js

While I was working on my validator demo, I noticed a few typos in the docs markdown folder.
I also noticed there were a couple places in the output where I'd meant to include a newline and forgot to. The formatting bugged me enough to make the small fix 🙂

Small docs/output fixes

---

packages/ruleset/src/functions/api-symmetry.js
packages/ruleset/test/api-symmetry.test.js

The `ibm-api-symmetry` code is losing track of the path to the canonical schema when "reference" schemas are resolved during processing, leading to false positives. This resolves the issue.

fix(ibm-api-symmetry): maintain paths when resolving reference schemas

---

packages/ruleset/src/functions/api-symmetry.js
packages/ruleset/test/api-symmetry.test.js

This PR fixes the ibm-api-symmetry rule to avoid false positives.

fix(ibm-api-symmetry): improve validation logic to avoid false positives

---

docs/ibm-cloud-rules.md

Add cautionary note to ruleset customization docs that disabling some rules may result in false negatives for other rules.

docs: add warning that certain rule customizations may result in false negatives

---

README.md

docs: add programmatic usage section to readme

---

package-lock.json
package.json

These are only development dependencies, so I'm not triggering a new release.

build(deps): force new version of sub-dependency micromatch

---

docs/ibm-cloud-rules.md
package-lock.json
packages/ruleset/src/functions/index.js
packages/ruleset/src/functions/optional-request-body.js
packages/ruleset/src/ibm-oas.js
packages/ruleset/src/rules/index.js
packages/ruleset/src/rules/optional-request-body-deprecated.js

This commit introduces the new "ibm-no-required-properties-in-optional-body" validation rule, and deprecates the "ibm-no-optional-properties-in-required-body" rule. Essentially, we're just changing the rule id, but we are providing backward compatibility by retaining (but deprecating) the old rule id.

feat(ibm-no-required-properties-in-optional-body): introduced new rule

---

docs/automated-quality-screening.md

Add rationale for automated quality screening scores.

docs: add documentation for automated quality screening

---

package-lock.json
package.json

See https://github.com/advisories/GHSA-gcx4-mw62-g8wm

build(deps): resolve rollup vulnerability

---

.secrets.baseline
docs/ibm-cloud-rules.md
packages/ruleset/src/functions/index.js
packages/ruleset/src/functions/required-enum-properties-in-response.js
packages/ruleset/src/ibm-oas.js
packages/ruleset/src/rules/index.js
packages/ruleset/src/rules/required-enum-properties-in-response.js
packages/ruleset/test/required-enum-properties-in-response.test.js
packages/ruleset/test/utils/root-document.js
packages/validator/src/scoring-tool/rubric.js
packages/validator/test/cli-validator/mock-files/oas3/err-and-warn.yaml
packages/validator/test/cli-validator/mock-files/oas3/just-warn.yml
packages/validator/test/cli-validator/mock-files/oas31/err-and-warn.yaml
packages/validator/test/cli-validator/tests/expected-output.test.js

This commit introduces the new "ibm-required-enum-properties-in-response" validation rule which will make sure that any enumerations defined within responses are defined as required, per API Handbook guidance.

feat(ibm-required-enum-properties-in-response): introduce new validation rule

---

.eslintrc.js
.github/pull_request_template.md
docs/openapi-ruleset-utilities.md
package-lock.json
package.json
packages/utilities/src/collections/index.js
packages/utilities/src/index.js
packages/utilities/src/utils/get-property-names-for-schema.js
packages/utilities/src/utils/get-schema-type.js
packages/utilities/src/utils/is-object.js
packages/utilities/src/utils/schema-has-constraint.js
packages/utilities/src/utils/schema-has-property.js
packages/utilities/src/utils/schema-loosely-has-constraint.js
packages/utilities/src/utils/schema-requires-property.js
packages/utilities/src/utils/validate-composed-schemas.js
packages/utilities/src/utils/validate-nested-schemas.js
packages/utilities/src/utils/validate-subschemas.js
packages/validator/package.json
scripts/generate-utilities-docs.js
scripts/templates/package.mustache

Generate dedicated documentation for constants and functions available in the utilities package.

docs: rework and expand docs for utilities package

---

.github/workflows/docker.yaml

This PR modifies docker.yaml so that the workflow is triggered when a new release of the validator package is published by semantic-release.

build: trigger docker workflow for new release
