package-lock.json, package.json
The engines property in the `package.json` is used to 
>  specify the version of node that your stuff works on
We already state in the README that Node v8.9.x is a prerequisite and we even have a module to enforce users have a supported version but I think it is best practice to have this defined in the `package.json`.
This will also _warn_ users if they install the package and are using an unsupported version so I am bumping the version so this ends up in the published module.
=> Add engine

package-lock.json, package.json, src/cli-validator/utils/preprocessFile.js, test/cli-validator/mockFiles/clean.yml
The API definition document for VPC contains the following line:
`"pattern": "^http(s)?:\\/\\/([^\\/?#]*)([^?#]*)(\\?([^#]*))?(#(.*))?$",`
This causes the validator to crash. The problem expression in the pattern about is `\\/`. It has already been known that an escaped solidus (`\/`) is a problem for the validator, and we are sanitizing them in the preprocessing step by converting them to an unescaped solidus (`/`).
The problem with this new pattern is that the preprocessor turns `\\/` into `\/`, which is the problem expression from before.
This PR addresses this case by generalizing the sanitation to correct any amount of escape characters before a solidus (`\/`, `\\/`, `\\\/`, etc.)
=> Debug VPC document

CHANGELOG.md, README.md, package-lock.json, package.json, src/cli-validator/index.js, src/cli-validator/runValidator.js, test/cli-validator/tests/optionHandling.js
This came up while looking at an issue with Allen - there was no obvious way to see which version he had installed locally. Since most CLI tools use the `-v` option to print the version, I decided to add this.
There was previously a `-v` arg for printing validator file names but that was a debug tool I made for myself and I can't imagine any users would use that, plus we are still in `0.x` so we can make breaking changes 😏 
In this PR...
- The `-v` option is updated to print the version
- The print validator version is changed to `-p`
- The logic for turning off coloring is simplified with a ternary operator
- The README is updated with new option and also correct some outdated statements (the npm `--save` option is now deprecated)
- The appropriate option handler test is updated
=> Add a "print version" option

src/plugins/utils/caseConventionCheck.js, test/plugins/caseConventionCheck.js
Fixes hang (exponentially long run time) of regex checks for case conventions.
Test cases included that exhibit the hang with the previous regexs.
=> Fix regex for camel case checks to avoid backtrack hangs.

package-lock.json, src/plugins/validation/2and3/semantic-validators/walker.js, test/plugins/validation/2and3/walker.js
This PR changes the validation of $refs to skip external refs, since these may have arbitrary structure. 
Also, non-conforming refs are now reported as warnings rather than errors, since the OAS spec allows references into other parts of the API doc, but these should still be discouraged.
Fixes #13
=> Change ref checker to skip external refs and flag issues as warnings

src/cli-validator/utils/validator.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/cli-validator/mockFiles/oas3/testoneof.yaml, test/plugins/validation/2and3/schema-ibm.js
This PR reworks the way schema-ibm finds and validates schema. The motivation for these changes was to handle "allOf", "anyOf", and "oneOf" constructs properly, but this evolved into some more fundamental changes in the process of development and debugging. I think the code is now simpler and more general.
I've added a test for the new functionality. I also did a before/after comparison of the validation of the Watson API docs, and found that the validator now reports errors for a number of previously undetected problems:
```
[mkistler@mkistlers-MacBook-Pro] ~/Projects/watson-developer-cloud/api-definitions (master)>lint-openapi apis-public/language-translator-v3.json 
errors
Message :   Property type+format is not well-defined.
Path    : …
```
=> Handle allOf, oneOf, anyOf schemas

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/cli-validator/mockFiles/clean.yml, test/cli-validator/mockFiles/cleanWithTabs.yml, test/cli-validator/mockFiles/errAndWarn.yaml, test/cli-validator/mockFiles/oas3/clean.yml, test/cli-validator/tests/expectedOutput.js, test/cli-validator/tests/optionHandling.js, test/plugins/validation/2and3/schema-ibm.js
This PR adds a validation rule for checking that all top-level schema -- within "definitions" of an OASv2 doc, or within "components/schemas" of an OASv3 doc -- contain a description.
The rationale for this rule is that JSON schema rules disallow a "description" sibling of a "$ref", so it is important for all "$ref"-able schema to have descriptions.
The default configuration for this rule is set to "warning" since it will generate _many_ messages for the Watson API docs.
=> Add validation rule for missing description in top-level schema

src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/validation/2and3/schema-ibm.js
As we learned from [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) recently,
> An additional primitive data type "file" is used by the Parameter Object and the Response Object to set the parameter type or the response as being a file.
This PR addresses the fact that the validator was giving errors for schemas with type file.
It's worth noting that `parameters-ibm` already supported allowing type file if the condition is met that it's a `formData` parameter.
After some consideration, my solution here is to allow type "file" for all schemas. My reasoning behind this is that it would be non-trivial to check whether or not models in `definitions` are being uses for response schemas or not. Additionally, schemas pretty much only appear in …
=> fix: dont error on schemas with type file for oas2 specs

test/plugins/validation/2and3/schema-ibm.js
@mkistler you stated in an issue that
> The validator currently checks properties and parameters to ensure that the type and format are "well-defined" -- meaning that they are explicitly defined in the OpenAPI spec. But it seems that the validator misses "schema" -- top-level entries under definitions -- that violate this rule.
This doesn't seem to be an issue anymore and was likely resolved by your recent work. For assurance, I added a quick test that seems to match your description of what wasn't working.
I also moved an OAS3 test from the Swagger2 section to the OAS3 section of the `schema-ibm` tests. A minor detail but worth correcting while I was updating the tests.
=> test: add type/format test for top level schema and move oas3 test

src/plugins/validation/2and3/semantic-validators/operation-ids.js, test/plugins/validation/2and3/operation-ids.js
Resolves #28 
Converts the `operation-ids` validation module, which checks for duplicated operation ids, to use `resolvedSpec` instead of `jsSpec`. This will allow it to pick up operations that live inside of referenced paths.
=> fix: exapand check for operation id duplciates to include referenced paths

README.md
`build-and-link` is outdated, should be `link`
=> docs: fix readme to show corrent npm script for building from source

package-lock.json, src/cli-validator/runValidator.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, src/plugins/validation/2and3/semantic-validators/walker-ibm.js, test/plugins/validation/2and3/walker-ibm.js
The validator was crashing on the COS spec due to some properties without values. While these were unintentional, the code should still be able to run fine.
This cleans up the areas blocking a successful run on that specific spec.
=> fix: handle null values for descriptions and schemas properties

README.md, src/.defaultsForValidator.js, test/cli-validator/mockFiles/clean.yml, test/cli-validator/mockFiles/cleanWithTabs.yml, test/cli-validator/mockFiles/errAndWarn.yaml, test/cli-validator/mockFiles/justWarn.yml, test/cli-validator/mockFiles/oas3/clean.yml, test/cli-validator/mockFiles/trailingComma.json, test/plugins/validation/2and3/operations-shared.js
This PR fixes the default case convention for operationIds to be lower_snake_case, to conform to the convention proscribed in the API Handbook.
=> Fix operationID case convention to match API Handbook

README.md, src/.defaultsForValidator.js, src/plugins/validation/oas3/semantic-validators/operations.js, test/plugins/validation/oas3/operations.js
Phil recommended this validation for the OpenAPI 3 transition. In OAS 3, the request body property of an operation does not have a "name" field. Having unnamed request bodies is not ideal for SDK generation so an annotation was introduced to add a name to the request body: `x-codegen-request-body-name`.
This PR validates that operations set this property and returns a `warning` if they do not. It only does this for non-form parameters, which I check for using a blacklist of mime types. Would love to get some feedback on any mime types I'm missing or if any I am using don't belong.
I also noticed that the other validation in `oas3/operations` was not configurable when it should have been, so that's been fixed as well.
=> feat: flag operations with non-form request bodies that do not specify a name

README.md
When we moved this project from the internal repo, one of the links in the README did not get updated. This fixes this and resolves #34
=> docs: update link to defaults folder from old repo to current one

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/walker-ibm.js, test/plugins/validation/2and3/walker-ibm.js
In the ongoing topic of descriptions that are siblings to $refs, we seem to have decided that they are sometimes beneficial and we've set the validation for that check to a default of `off`. That said, @padamstx thought it would be a good idea to let users know when they are using $ref sibling descriptions unnecessarily. This PR adds a validation that checks if $ref sibling descriptions are identical to the description in the schema that they reference (so, redundant).
This wasn't an easy validation to describe, so happy to change the message or the config property name if someone has other ideas.
=> flag descriptions sibling to `$ref` if identical to referenced description

.gitignore
Insignificant change to additionally ignore IntelliJ/Webstorm project information.
Does not change anything functionally in any code, just nicer for people like me
who develop JavaScript in WebStorm.
=> docs: added .gitignore of .idea/ directories

README.md, src/.defaultsForValidator.js, src/plugins/utils/caseConventionCheck.js, src/plugins/validation/2and3/semantic-validators/paths-ibm.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/caseConventionCheck.js, test/plugins/validation/2and3/paths-ibm.js, test/plugins/validation/2and3/schema-ibm.js
This change adds support for a couple of new case conventions to round out case convention
support, upper_snake_case and upper_dash_case.  Additionally it includes support for explicit
and independent control of the case convention for paths (paths_case_convention), schema
properties (property_case_convention), and schema enums (enum_case_convention).  These options
are disabled by default so as not to impact current usage of snake_case_only and thus are
backwards compatible. In order to use them, a user must turn off the corresponding
'snake_case_only' option and enable these options.  Full automated tests are included.
Closes #38, #40
=> feat: added explicit control of case conventions in paths, properties and enums

src/cli-validator/index.js, src/cli-validator/runValidator.js, src/cli-validator/utils/printJsonResults.js, test/cli-validator/tests/optionHandling.js
This revision adds a new --json option to the cli-validator that prints the internal
result data in json format to stdout.  It does additionally include the line number
as a 'line' field in the JSON (this is not in the internal json data).  Automated
test validates that json is received.
Closes #43
=> feat: Added -j/--json output option to cli-validator

src/plugins/validation/2and3/semantic-validators/security-definitions-ibm.js, test/plugins/validation/2and3/security-definitions-ibm.js
replaced instances of jsSpec with resolvedSpec in security-definitions-ibm so that resolved paths can be accessed when referenced, also added a test.
fixes #39
=> Security definition referencing

.gitignore, README.md, package-lock.json, package.json
This revision adds a dependency on the 'pkg' tool to create standalone binaries
for Linux, MacOS, and Windows that do not depend on node.js being installed. To
run the tool, run 'npm run pkg' and the binaries will be created in a 'bin'
directory in the root.
Closes #48
=> feat: added build of platform specific standalone binaries

src/cli-validator/utils/processConfiguration.js
It turns out that the findUp method cannot handle a full path to a file as input. When this
is passed in, it redudantly or completely incorrectly prepends the current working directory
to the front of the returned path.  Work around is to split any path information off of the
input path and pass the path portion into the method as opt.cwd.
Closes #55
=> fix: issue 55 problems when filename with path is passed to --config

src/plugins/validation/oas3/semantic-validators/operations.js, test/plugins/validation/2and3/paths-ibm.js, test/plugins/validation/2and3/walker-ibm.js, test/plugins/validation/oas3/operations.js
Passing in a dot-separated string to `lodash/at` is problematic when one of the segments contains a period itself. This PR sanitizes the dot separated strings by using square bracket notation instead.
Test cases added to ensure fix.
Resolves #53
=> fix: don't crash validator when path has a period in it

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/operations-shared.js, test/plugins/validation/2and3/operations-shared.js
if there is a tag in operation tags that isn't in the top level tags then a warning will be raised
=> fix: raises warning for tag that hasnt been defined in tags

src/cli-validator/runValidator.js, test/cli-validator/mockFiles/multi-file-spec/main.yaml, test/cli-validator/mockFiles/multi-file-spec/schema.yaml, test/cli-validator/tests/expectedOutput.js
This fixes a bug caused by running the validator on a multi-file definition from any directory other than that of the root file.
The issue is that we read the API definition contents and store them in memory before we run the ref resolver package. When we run the resolver, it has no way to know the context of the original file so it uses the current working directory, the directory from which the command was executed.
One potential solution was to pass the filepath directly to the resolver. It can handle reading in the file and resolving references based on the location of the file as it should. The problem with this solution is that we lose all of the preprocessing we do to remove problematic characters from the document. This leads to the inability to run the validator on files that we …
=> fix: use correct working dir when resolving multi-file definitions

src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/validation/2and3/schema-ibm.js
Validator will skip validation of non-string enum values.
=> fix: skips validation for non-string enum values

src/plugins/validation/2and3/semantic-validators/walker.js, test/plugins/validation/2and3/walker.js
walker.js now recognizes links in components and adds it to the dictionary so the validator no longer returns an error asking for the response link refs to be formatted as responses instead of following the format of '#/components/links'.
=> fix: response links are not validated as responses

src/plugins/validation/2and3/semantic-validators/operations-shared.js, test/plugins/validation/2and3/operations-shared.js
The validator was mistakenly checking only GET operations for array responses. This PR switches the logic to check _any_ operation, which is how we describe the check in our documentation. Test cases adjusted to verify this logic.
Resoves #71
=> fix: flag any operations with array responses

src/plugins/validation/2and3/semantic-validators/responses.js, test/plugins/validation/2and3/responses.js
validator now recognizes oneOf, allOf, and anyOf and will only issue a warning if the lists contain inline schemas instead of only refs
=> Response schemas

src/plugins/validation/2and3/semantic-validators/walker.js, test/plugins/validation/2and3/walker.js
validator now recognizes that links is only a feature of oas3
=> fix: links is only supported by oas3

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/walker.js, test/plugins/validation/2and3/walker.js
Makes the check for $ref patterns configurable with flag `incorrect_$ref_pattern`. I am open to changing that name. Documentation and defaults updated.
Also changes a test in `walker` that was previously overwriting the entire walker config object - not good for adding more tests!
Resolves #77
=> fix: make $ref pattern check configurable

README.md, src/.defaultsForValidator.js, test/cli-validator/tests/configFileValidator.js, test/cli-validator/tests/expectedOutput.js, test/cli-validator/tests/optionHandling.js, test/plugins/validation/2and3/parameters-ibm.js
Changes in the configs to accommodate to the API handbook rules that say that all 'MUST' guidelines should be defaulted to errors
=> Config changes

README.md, src/plugins/validation/2and3/semantic-validators/parameters-ibm.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/validation/2and3/parameters-ibm.js, test/plugins/validation/2and3/schema-ibm.js
This PR bypasses the case_convention checks on parameters and properties that are marked as `deprecated: true`.
I also slipped in a few minor documentation updates to the README.
=> Skip case_convention checks on deprecated parameters and properties

src/cli-validator/utils/preprocessFile.js
This PR fixes a crash in the validator when the input API document contains a `x9d` character.  This problem was revealed by the open-service-broker API doc.
The fix is to simply replace these characters with space characters before calling the JSON/YAML parser.
=> fix: filter out #9d chars from input

src/plugins/utils/checkSnakeCase.js, src/plugins/utils/index.js, src/plugins/utils/isParameter.js, src/plugins/validation/2and3/semantic-validators/items-required-for-array-objects.js, src/plugins/validation/2and3/semantic-validators/operations-shared.js, src/plugins/validation/2and3/semantic-validators/parameters-ibm.js, src/plugins/validation/2and3/semantic-validators/paths-ibm.js, src/plugins/validation/2and3/semantic-validators/responses.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, src/plugins/validation/2and3/semantic-validators/walker-ibm.js, src/plugins/validation/2and3/semantic-validators/walker.js, src/plugins/validation/oas3/semantic-validators/parameters.js, src/plugins/validation/oas3/semantic-validators/responses.js, src/plugins/validation/swagger2/semantic-validators/parameters.js, test/plugins/validation/oas3/parameters.js
The fix we posted for determining if an object was actually a Parameter (and not just something named parameters) was done in the shared validator but I forgot about the spec version specific validators. This refactors that logic out into its own module to be shared across the validators.
Also, I refactored the validator utils into single module for cleaner importing.
Also, I removed the `checkSnakeCase` module - it was replaced by `caseConventionCheck` and was duplicated code. No reason for it to be there anymore. Updated the validators still using it to use the new method.
=> fix: use parameter-determining method in all parameters validations

src/plugins/validation/2and3/semantic-validators/paths.js, test/plugins/validation/2and3/paths.js
This file assumes `parameters` will be an array and calls the `map` method on it. This prevents it from doing so if parameters is not an array.
Resolves #101
=> fix: prevent crash when `parameters` is illegally not an array

README.md, src/.defaultsForValidator.js, src/plugins/utils/caseConventionCheck.js, test/plugins/caseConventionCheck.js
The Kubernetes API conventions use lower_camel_case except for acronyms which are expected to be all the same case.  When an acronym is not at the beginning of the string it should be capitalized.
This change adds a new validator called k8s_camel_case that relaxes lower_camel_case to allow this.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions
fix #105
=> feat(plugin): adds k8s_camel_case validator for k8s API conventions

src/plugins/validation/2and3/semantic-validators/security-definitions-ibm.js, src/plugins/validation/2and3/semantic-validators/security-ibm.js, test/plugins/validation/2and3/security-definitions-ibm.js, test/plugins/validation/2and3/security-ibm.js
Multiple security schemes are now considered as valid and flagged as used.
Added unit tests for the new code.
Fixes #108
=> fix: Consider as valid multiple schemes in a security requirement object

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/paths-ibm.js, test/plugins/validation/2and3/paths-ibm.js
This PR adds a rule, with default configuration of 'warn', that flags identical path parameters defined on the individual operations of a path.  These parameters should be defined on the path object.
Note that only completely identical parameters are flagged -- variations in the parameter description will suppress the warning.
=> Add rule to check for duplicate path parameters

src/cli-validator/utils/validator.js, src/plugins/validation/oas3/semantic-validators/responses.js, test/plugins/validation/oas3/responses.js
This PR adds a check for a 204 response that defines a response body.  I defined this rule as an error and did not make it configurable since returning a response body with a 204 response violates the HTTP spec:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5
The PR also contains a fix for a latent problem in the validator that was exposed by this new feature -- semantic validators with the same name as a shared (`2and3`) validator were not being run.
=> Add check for 204 response with response body

src/plugins/validation/2and3/semantic-validators/paths-ibm.js, test/plugins/validation/2and3/paths-ibm.js
This PR fixes a bug with the logic of the duplicate path parameter checks that causes an exception when an operation has no parameters.  I've added a test for this case as well.
=> fix: Fix duplicate parameter checking when all parameters are defined at the path level

README.md, src/.defaultsForValidator.js, src/plugins/validation/oas3/semantic-validators/pagination-ibm.js, test/cli-validator/mockFiles/oas3/clean.yml, test/plugins/validation/oas3/pagination-ibm.js
This PR adds a rule that checks paginated list operations for conformance to basic requirements of the API Handbook for paginated collections.  All checks are grouped under a single rule that is set to "warning" by default.
I've only implemented this rule for oas3 schemas.  The oas2 support would require significant additional logic and I considered it not worth the effort, at least for this initial PR.  Support for oas2 could be added later if necessary.
=> Add rule to check pagination list operations conform to API Handbook

package-lock.json, package.json
This PR fixes many of the vulnerabilities reported by `npm audit`.  This was inspired by the `dependabot` PR #113, but goes a bit further.  Prior to these changes, `npm audit` reported:
```
found 171 vulnerabilities (15 low, 2 moderate, 153 high, 1 critical)
```
And after these changes, we have
```
found 19 vulnerabilities (3 low, 1 moderate, 15 high)
```
The fixes suggested by `npm audit` for the remaining 15 "high" vulnerabilities did not work, so I'm letting those pass for now.
=> Fix many vulnerabilities reported by npm audit

src/cli-validator/index.js
Making the change @BigBlueHat suggested in #120 :
Was:
> Usage: index [options] [command] [<file>]
Now:
> Usage: lint-openapi [options] [command] [<file>]
=> fix: add command name for improved usage output

src/plugins/validation/swagger2/semantic-validators/operations-ibm.js, test/plugins/validation/swagger2/operations-ibm.js
Currently, swagger2 validator reports error on all PUT or POST operations that has no consume field. This is technically incorrect because a POST operation is not required to have a request body and if there is no request body, there does not need to be a consumes field.
The fix now checks for body parameters on the path level and also operation level, and will only report error when there is body parameter, but no consume field.
=> fix: swagger2 validator should only report error if there's body parameter but no consume

src/plugins/validation/2and3/semantic-validators/operation-ids.js, test/cli-validator/mockFiles/clean.yml, test/cli-validator/mockFiles/cleanWithTabs.yml, test/cli-validator/mockFiles/oas3/clean.yml, test/cli-validator/tests/expectedOutput.js, test/cli-validator/tests/optionHandling.js, test/plugins/validation/2and3/operation-ids.js
[documentation for operation Id naming convention
](http://watson-developer-cloud.github.io/api-guidelines/swagger-coding-style#operationid)
We should add support to the validator to check for conformance to these conventions and report any non-conformance as a warning
This PR takes the following approach to check for operationId naming convention: 
- Only consider paths `p` for which `p` and `p/{param}` exist, `p` has a GET and POST path, and `p/{param}` has a GET, a DELETE, and a POST or PUT or PATCH.
- For paths that satisfy this constraint, we verify that
- the operationId for GET on `p` starts with "list"
- the operationId for POST on `p` starts with "create" or "add"
- the operationId for GET on `p/{param}` starts with "get"
- the operationId for DELETE on `p/{param}` starts with …
=> feat: operationId should conform to naming convention

src/plugins/validation/oas3/semantic-validators/security-definitions-ibm.js
The `tokenUrl` property for the OAuth2 password flow has the `Url` part incorrectly capitalised (`tokenURL`), causing false errors. All other properties tested in this validation have the correct case.
=> Fix incorrect property case

README.md, package-lock.json, src/.defaultsForValidator.js, src/plugins/validation/oas3/semantic-validators/responses.js, test/cli-validator/mockFiles/oas3/clean.yml, test/plugins/validation/oas3/responses.js
Related Issue: [arf/planning-sdk-squad/issues/560](https://github.ibm.com/arf/planning-sdk-squad/issues/560)
Changes:
- added logic to check for response bodies in non-204 success responses in the oas3 plugin
- added a test to check that a non-204 success response without response body generates a warning
- added a test to check that multiple non-204 success responses without response bodies generates multiple warnings
- updated the README.md to help users resolve potential issue with `npm run link`
- fixed API definitions and tests that define a non-204 success without adding a response body
=> feat: add warning, non-204 success response should have response body

src/plugins/validation/oas3/semantic-validators/responses.js, test/plugins/validation/oas3/responses.js
Changes:
- use the resolvedSpec (all $refs dereferenced) to check if a response has content
- removed the isRef variable because the resolvedSpec should not contain references
Tests:
- added a test that defines a spec with a reference to a response, preprocesses the spec and dereferences the response, then validates the response
Related issue: #135
=> fix: non-204 successes with reference to response

package-lock.json, package.json, src/cli-validator/index.js, src/cli-validator/utils/modified-commander.js, test/cli-validator/tests/optionHandling.js
When an unsupported option is given, a single-line error is printed. Now, the usage menu is printed along with the single-line error.
Change: 
- unsupportedOptionError.js modifies the commander code
- modified index.js file to include the unsupportedOptionError.js file.
Commander code was:
```
Command.prototype.unknownOption = function(flag) {
if (this._allowUnknownOption) return;
console.error();
console.error(" error: unknown option %s'", flag);
console.error();
process.exit(1);
};
```
Now:
```
program.unknownOption = function(flag) {
if (this._allowUnknownOption) return;
console.error();
console.error(" error: unknown option %s'", flag);
console.error();
// this is the extra code added to the function
this.outputHelp();
process.exit(1);
};
```
=> fix: print error message and the usage menu for an unknown command line argument

src/plugins/validation/2and3/semantic-validators/operation-ids.js, src/plugins/validation/oas3/semantic-validators/openapi.js, src/plugins/validation/swagger2/semantic-validators/swagger.js, test/plugins/validation/2and3/operation-ids.js, test/plugins/validation/oas3/openapi.js, test/plugins/validation/swagger2/swagger.js
This feature is in done in response to https://github.com/IBM/openapi-validator/issues/126
Currently, our validator does not check the existence of mandatory field `openapi` in openapi3 api definitions, or `swagger` field in swagger2 api definitions.
This PR allows validator to check for the fields, as well as validate the field type and value.
=> feat: validator should check for mandatory swagger or openapi field

README.md, src/.defaultsForValidator.js, src/plugins/utils/findOctetSequencePaths.js, src/plugins/validation/2and3/semantic-validators/parameters-ibm.js, src/plugins/validation/oas3/semantic-validators/operations.js, src/plugins/validation/oas3/semantic-validators/parameters.js, src/plugins/validation/oas3/semantic-validators/responses.js, test/plugins/validation/2and3/parameters-ibm.js, test/plugins/validation/oas3/operations.js, test/plugins/validation/oas3/parameters.js, test/plugins/validation/oas3/responses.js
Changes:
- added a findOctetSequencePaths function to handle the logic of finding schema type: string, format: binary for cases of nested arrays, objects, nested arrays of type object, objects with properties that are nested arrays, and objects with properties that are objects, and the simple case where a schema uses type: string, format: binary directly. This function takes a resolved schema and returns a list of paths to octet sequences (empty list if none found). The function accepts the path both as an array and a string and returns the path in the same format received.
- added logic to handle application/json request bodies that use schema type: string, format: binary
- added logic to handle application/json response bodies of type: string, format: binary
- added logic to handle …
=> feat: add warning for binary string in "application/json" or parameter

src/plugins/validation/2and3/semantic-validators/refs.js, test/plugins/validation/2and3/refs.js
Changes:
- added checks for parameters, responses, and other definitions in the components section that are not used in the API definition
- updated comments in refs.js
- restructured refs.js as needed to support checking components.parameters and components.responses
Tests:
- added tests to that ensure that a warning is issued when a response or parameter definition is not used
- added tests to ensure a warning is not issued when a response or parameter definition is used
=> feat: flag definitions that are defined but never used

src/plugins/validation/2and3/semantic-validators/parameters-ibm.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/validation/2and3/parameters-ibm.js, test/plugins/validation/2and3/schema-ibm.js
Changes:
- changed function name formatValid to typeFormatErrors
- passed additional arguments (messages and checkStatus) to be able to record errors within the function
- negated the boolean conditions used to determine if the type+format is valid and (instead of using the boolean logic to return the validity of the schema) used the negated logic to record errors
- added descriptive messages to help resolve the type+format errors
- removed the duplicate type+format validation function in parameters-ibm.js
- added parameters to the list of schemas to validate
- moved validation for swagger2 file parameters into 'file' section of typeFormatErrors. I believe this is the only validation that was done in parameters-ibm that is not handled by typeFormatErrors.
Tests:
- added a test to ensure …
=> feat: list valid types and formats in error messages

README.md
Related to #110 - adding info to the README on running the validator with Docker.
=> Add Docker image as installation option in README

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/operation-ids.js, test/plugins/validation/2and3/operation-ids.js
Naming conventions for operationId should be configurable. 
Change:
- added config option to README.md and .defaultsForValidator.js
- added config logic to operation-ids.js 
- added a test case to exercise the new behavior
Related: [Issue 148](https://github.com/IBM/openapi-validator/issues/148)
=> fix: config option for operationId naming convention

src/cli-validator/utils/circular-references-ibm.js, src/plugins/validation/2and3/semantic-validators/paths-ibm.js, src/plugins/validation/2and3/semantic-validators/security-definitions-ibm.js, src/plugins/validation/2and3/semantic-validators/walker-ibm.js, src/plugins/validation/2and3/semantic-validators/walker.js, test/plugins/validation/2and3/paths-ibm.js, test/plugins/validation/2and3/security-definitions-ibm.js, test/plugins/validation/2and3/walker.js
This PR fixes a few crashes I encountered when running the validator against the OpenShift API doc and an API doc for the Power IaaS service.
One problem was caused by a schema with a property named "$ref", which the validator mistook for an actual "$ref" in a couple of places.
Another problem was the way paths were represented as strings for messages in `paths-ibm.js`. The problem is that OpenShift uses periods in some of its path segments, so the line number resolution was failing for any problems reported on one of these paths.  Switching to representing the paths as an array of path elements fixes that problem.
Then there was a crash attempting to reference `scopes` within an "oauth2" security definition when it was not present.  In fairness, `scopes` is required when `type` is …
=> fix: Fix crashes found on real API docs

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/validation/2and3/schema-ibm.js
Properties with the same name but different type are allowed in an API definition. However, that would not constitute good, consistent design within an API. Therefore, the validator should catch properties that follow this pattern and produce a warning. 
Change:
- Modified schema-ibm.js to find properties with the same name but different type in the API definition.
- added an API definition and a test to exercise the new behavior.
=> feat: catch properties with the same name but different type.

README.md, src/.defaultsForValidator.js, src/plugins/validation/oas3/semantic-validators/responses.js, test/plugins/validation/oas3/responses.js
Reason:
- IBM Handbook says 400 response should be used instead of 422
- IBM Handbook prefers 303 and 307 responses over 302
Changes:
- added warning for 422 response codes
- added warning for 302 response codes
- added ibm_status_code_guidelines config option with default warning
Tests
- added a test to ensure warning issued for 422 response
- added a test to ensure warning issued for 302 response
=> feat: adds a default warning for 422 and 302 responses

README.md, src/plugins/validation/2and3/semantic-validators/operation-ids.js, test/cli-validator/tests/expectedOutput.js, test/cli-validator/tests/optionHandling.js, test/plugins/validation/2and3/operation-ids.js
This PR makes two small changes to operationId naming convention validation.  First, it makes a small change to the message generated (replacing a period with a colon) so that all the operationId naming convention errors are summarized together in the summary display. It also restricts the naming convention check to only be applied to "resource-oriented" operations.  This is to prevent false positives on operations such as Watson Language Translator `translate` (`POST` on `/v3/translate`).
=> Rework operationId naming convention checks

src/plugins/validation/2and3/semantic-validators/operation-ids.js, test/plugins/validation/2and3/operation-ids.js
This PR refactors the code to perform the operationId naming convention check.  The new implementation separates the code that determines the name prefix from the actual check logic so that checking is only done in one place, using the previously computed verbs.  It also changes the check from a `match` to a `startsWith`, to avoid making assumptions about the allowed characters in the remainder of the operationId.
=> Refactor operationId naming convention check

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/validation/2and3/schema-ibm.js
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1653
When there are two property names of different conventions but equivalent names, an error with be reported. (e.g. `propName` and `prop_name` exist)
=> feat: Added check for case collsions of property names

src/plugins/validation/2and3/semantic-validators/paths-ibm.js, test/plugins/validation/2and3/paths-ibm.js, test/plugins/validation/2and3/schema-ibm.js
Before, if some operations on a path defined redundant path parameters but others didn't define _any_ parameters, the code would crash. This solves that bug.
Also, this fixes a slight mishap in the tests for a recent PR. I came across the happy discovery that our tests were reporting an exit code of `0` regardless of failing tests. So the build from the previous PR didn't fail despite a failing test showing up in the logs. Lots of fun.
In this PR, I'm just fixing the malformed test. In my next PR, I'm going to move the repo to use `jest` instead of `mocha`, as this seems to be a `mocha` bug. All of our tests are cross compatible so it shouldn't be too much effort.
=> fix: dont crash when only a subset of ops contain redundant path params

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/operations-shared.js, test/cli-validator/mockFiles/clean-with-tabs.yml, test/cli-validator/mockFiles/clean.yml, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/option-handling.test.js, test/plugins/validation/2and3/operations-shared.test.js
- The current `unused_tag` now checks for tags defined in `tags` section but not used in any operation.
- The new `undefined_tag` checks for tags used in operations but not defined in `tags` section (previous `unused_tag` behaviour)
> Discussed in #170
=> Issue 170 tag checks refactor

README.md, src/.defaultsForValidator.js
This PR reduces the default severity of the messages issued for enum case convention check from error to warning.
=> Reduce default severity of enum case convention

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/items-required-for-array-objects.js, test/plugins/validation/2and3/items-required-for-array-objects.test.js
Required property definitions are now checked for in objects that have allOfs, anyOfs, and refs. Also if they are not defined it is only a warning since "required" properties are not required to be defined anywhere.
I added an extra util function for reducing an object (resolving it's refs) since I did not see an easy way of getting an object in the jsSpec using only the ref path. Let me know if there is an easier way.
=> fix: Required properties warning now checked in child refs

src/plugins/validation/oas3/semantic-validators/security-definitions-ibm.js
When running the validator against an OpenAPI 3 document, the validator can fail with the error: 
```
[Error] There was a problem with a validator.
stringValidator.isurl is not a function
TypeError: stringValidator.isurl is not a function
at Object.module.exports.validate (~/.nvm/versions/node/v12.14.1/lib/node_modules/ibm-openapi-validator/src/plugins/validation/oas3/semantic-validators/security-definitions-ibm.js:168:26)
at ~/.nvm/versions/node/v12.14.1/lib/node_modules/ibm-openapi-validator/src/cli-validator/utils/validator.js:65:45
at Array.forEach (<anonymous>)
at validateSwagger (~/.nvm/versions/node/v12.14.1/lib/node_modules/ibm-openapi-validator/src/cli-validator/utils/validator.js:64:35)
at processInput (~/.nvm/versions/node/v12.14.1/lib/node_modules/ibm-openapi-validator/src/cli- …
```
=> fix(validator): typo in `isURL` function call

.travis.yml, src/plugins/utils/index.js, src/plugins/utils/is-response.js, src/plugins/validation/2and3/semantic-validators/items-required-for-array-objects.js, src/plugins/validation/2and3/semantic-validators/responses.js, src/plugins/validation/oas3/semantic-validators/responses.js, test/plugins/utils/is-response.test.js, test/plugins/validation/oas3/responses.test.js
Previously, the only way we checked for a response object was by checking for the string "responses" in the path at a certain location. This would cause schema properties named `responses` to be validated as if it were a response. This would cause confusing warnings/errors.
This PR introduces robust logic to prove that the object in question is in fact, a response.
Additionally, I fixed some linting issues and added a linting step to the Travis build so that these things won't go uncaught in the future.
Resolves #188
=> fix: dont validate schema properties called 'responses' as responses

src/plugins/validation/oas3/semantic-validators/operations.js, test/plugins/validation/oas3/operations.test.js
=> fix(validator): Spurious errors when using `application/merge-patch+json` media type

src/cli-validator/runValidator.js, test/spectral/mockFiles/oas3/file-resolver/subdir/main.yaml, test/spectral/mockFiles/oas3/file-resolver/subdir/schema.yaml, test/spectral/mockFiles/oas3/url-reference-resolver/main.yaml, test/spectral/mockFiles/swagger/file-resolver/subdir/main.yaml, test/spectral/mockFiles/swagger/file-resolver/subdir/schema.yaml, test/spectral/mockFiles/swagger/url-reference-resolver/main.yaml, test/spectral/tests/path-resolve.test.js
Fixes an issue where Spectral wasn't correctly resolving file references when the file(s) to validate were not in the current working directory the validator was invoked. The fix was to temporarily switch to the directory to the location of the file we're validating, following what our "default" validator does.
Unit tests were also added to test file/remote url resolving
Resolves #199
=> fix: spectral file path resolving

src/.defaultsForValidator.js, src/cli-validator/runValidator.js, src/cli-validator/utils/processConfiguration.js, src/lib/index.js, src/spectral/utils/spectral-validator.js, test/spectral/mockFiles/mockConfig/.mockSpectral.yaml, test/spectral/tests/spectral-validator.test.js
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/2170
followup of: https://github.com/IBM/openapi-validator/pull/195
These changes allow spectral rules to have their severity level changed in the `.validatrc` and allow custom rules defined in a `.spectral.yaml` file to not be overridden by the `.defaultsForSpectral.yaml`. Although the `.defaultsForSpectral.yaml` will still override the `.spectral.yaml` severity level of any existing rule `.defaultsForSpectral.yaml` defines a severity for, including the extended rules.
=> feat: allow spectral rules to be defined in the validaterc

package-lock.json, package.json, src/cli-validator/runValidator.js
While working on arf/planning-sdk-squad#2400, I discovered that the old version of chalk we were using in the validator does not support the newer and more rationale color constants in the latest version, so this PR is a simple upgrade to the latest version to make these new colors available.
=> refactor: upgrade chalk package to latest level

README.md, src/cli-validator/runValidator.js, src/cli-validator/utils/printResults.js, src/cli-validator/utils/processConfiguration.js, src/cli-validator/utils/validator.js, src/plugins/utils/messageCarrier.js, src/spectral/utils/spectral-validator.js, test/cli-validator/mockFiles/oas3/err-and-warn.yaml, test/cli-validator/tests/config-file-validator.test.js, test/cli-validator/tests/info-and-hint.test.js, test/cli-validator/tests/option-handling.test.js, test/spectral/mockFiles/mockConfig/info-and-hint.yaml, test/spectral/tests/disabled-rules.test.js, test/spectral/tests/enabled-rules.test.js, test/spectral/tests/info-and-hint.test.js
This PR extends the set of severity levels supported by the validator to include "info" and "hint".  This improves the integration with Spectral, which already supports these severity levels, and gives us new options for providing guidance to service teams on their API design.
The second commit is a small but significant change in the Spectral tests that improves performance by avoiding redundant invocations of the validator.  The result is that the time to run the whole test suite is reduced by over 50% -- from 17s to around 8s on my system.
=> Add support for "info" and "hint" severity levels

README.md, src/cli-validator/index.js, src/cli-validator/runValidator.js, src/cli-validator/utils/printResults.js, src/plugins/utils/messageCarrier.js, src/plugins/validation/2and3/semantic-validators/operations-shared.js, src/plugins/validation/2and3/semantic-validators/parameters-ibm.js, src/plugins/validation/2and3/semantic-validators/paths-ibm.js, src/plugins/validation/2and3/semantic-validators/responses.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, src/plugins/validation/2and3/semantic-validators/security-definitions-ibm.js, src/plugins/validation/2and3/semantic-validators/security-ibm.js, src/plugins/validation/2and3/semantic-validators/walker-ibm.js, src/plugins/validation/2and3/semantic-validators/walker.js, src/plugins/validation/oas3/semantic-validators/dummy-ibm.js, src/plugins/validation/oas3/semantic-validators/operations.js, src/plugins/validation/oas3/semantic-validators/pagination-ibm.js, src/plugins/validation/oas3/semantic-validators/parameters.js, src/plugins/validation/oas3/semantic-validators/responses.js, src/plugins/validation/swagger2/semantic-validators/dummy-ibm.js, src/plugins/validation/swagger2/semantic-validators/operations-ibm.js, src/spectral/utils/spectral-validator.js, test/cli-validator/tests/expected-output.test.js, test/plugins/utils/message-carrier.test.js, test/plugins/validation/2and3/paths-ibm.test.js, test/plugins/validation/2and3/paths.test.js, test/plugins/validation/swagger2/form-data.test.js
This PR adds the ability to display the associated rule name for each issue reported by the validator.  Since this makes the already lengthy output longer, this feature must be enabled with a command line option.  I chose to use the `verbose` option, but this does come at some cost -- namely that the `-v` that previously was an alias of `--version` is now aliased to `--verbose`.  Note that `--version` is still supported and works as previously.
The bulk of the content in this PR was originally developed by @barrett-schonefeld and submitted in PR #147 way back in February.  I just had to make a few changes, add some tests, and update the README.
=> Display rule names for messages in verbose mode

README.md, src/cli-validator/index.js
This PR reorders the CLI options in both the CLI help and in the README to be in (mostly) alpha order.  The prior ordering seemed somewhat arbitrary making it harder to find specific options.
=> docs(cli): show cli options in alpha order

src/.defaultsForValidator.js, src/spectral/rulesets/.defaultsForSpectral.yaml, test/spectral/mockFiles/oas3/enabled-rules.yml, test/spectral/tests/enabled-rules.test.js, test/spectral/tests/spectral-config.test.js
This PR changes the severity of the spectral rules ``oas2-valid-definition-example`` and ``oas3-valid-schema-example`` from ``error`` to ``warn``. The spectral rule ``oas3-valid-oas-content-example`` was also enabled with a ``warn`` severity, since the linked issue reported our validator was not reporting warnings in request or response body examples. 
The ``src/.defaultsForValidator.js`` file was also updated to match the values in our default spectral ruleset.
fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/2303
=> chore: decrease severity of valid schema/content example validation

README.md, src/.defaultsForValidator.js, src/plugins/validation/2and3/semantic-validators/schema-ibm.js, test/plugins/validation/2and3/schema-ibm.test.js
=> feat: exclude common inconsistent property names

src/cli-validator/utils/processConfiguration.js, test/plugins/validation/2and3/schema-ibm.test.js
After upgrading to 0.34.0, I want to use some custom ignore names for `inconsistent_property_type` such as:
```json
"schemas": {
...
"inconsistent_property_type": ["warning", ["year"]],
...
}
```
But got an error:
```
TypeError: Cannot read property 'includes' of undefined
at validateConfigOption (/usr/local/lib/node_modules/ibm-openapi-validator/src/cli-validator/utils/processConfiguration.js:369:21)
at /usr/local/lib/node_modules/ibm-openapi-validator/src/cli-validator/utils/processConfiguration.js:118:28
at Array.forEach (<anonymous>)
at /usr/local/lib/node_modules/ibm-openapi-validator/src/cli-validator/utils/processConfiguration.js:76:17
at Array.forEach (<anonymous>)
at /usr/local/lib/node_modules/ibm-openapi-validator/src/cli-validator/utils/processConfiguration.js:63:20
at …
```
=> fix(function): Fix error when adding custom ignore names for inconsistent_property

src/.defaultsForValidator.js, src/plugins/validation/oas3/semantic-validators/responses.js, test/plugins/validation/oas3/responses.test.js
Currently `101` is not considered a success and therefore it's not valid for an operation to support `101` without also supporting a `2xx` code. In fact, we'd prefer to validate that `101` *MUST NOT* be used along with a `2xx` response code.
=> Add validation for use of 101 status code

.releaserc
The `semantic-release` API changed with its latest major release and now uses
"branches" instead of "branch" to specify which branch to release on.
=> fix: update releaserc to use main branch

src/cli-validator/runValidator.js, src/cli-validator/utils/circular-references-ibm.js, src/plugins/ast/ast.js, src/plugins/validation/2and3/semantic-validators/info.js, src/plugins/validation/2and3/semantic-validators/items-required-for-array-objects.js, src/plugins/validation/2and3/semantic-validators/paths.js, src/plugins/validation/oas3/semantic-validators/discriminator.js, src/plugins/validation/swagger2/semantic-validators/form-data.js, src/plugins/validation/swagger2/semantic-validators/parameters.js, src/plugins/validation/swagger2/semantic-validators/security-definitions.js, test/plugins/validation/2and3/items-required-for-array-objects.test.js, test/plugins/validation/oas3/discriminator.test.js
This resolves Issue #241.
I made the following changes:
=> fix: object type validations

README.md, src/plugins/validation/swagger2/semantic-validators/form-data.js, src/spectral/rulesets/.defaultsForSpectral.yaml, test/plugins/validation/oas3/responses.test.js, test/plugins/validation/swagger2/form-data.test.js, test/spectral/mockFiles/swagger/disabled-rules.yml, test/spectral/mockFiles/swagger/enabled-rules.yml, test/spectral/tests/disabled-rules.test.js, test/spectral/tests/enabled-rules.test.js, test/spectral/tests/spectral-validator.test.js
Addresses:
- Desire to simplify the validator ruleset by using an equivalent Spectral rule
Changes:
- Enable the oas2-operation-formData-consume-check Spectral rule
- Remove the in-code validation of this rule
Tests:
- Remove irrelevant disable-rules tests
- Remove irrelevant test for in-code validation of the `formData consumes` rule
- Update swagger/disable-rules.yml to remove the violation of the `formData consumes` rule
- Fix incongruities between swagger/disable-rules.yml and swagger/disable-rules-in-memory.js by loading swagger/disable-rules.yml into memory
- Add a test to enabled-rules.test to ensure the Spectral rule is enabled and produces a warning for rule violation
=> refactor: use Spectral to validate `consumes` property with formData param

src/cli-validator/utils/buildSwaggerObject.js, src/plugins/validation/2and3/semantic-validators/operations-shared.js, src/spectral/rulesets/.defaultsForSpectral.yaml, test/plugins/validation/2and3/operations-shared.test.js, test/spectral/mockFiles/oas3/disabled-rules.yml, test/spectral/mockFiles/oas3/enabled-rules.yml, test/spectral/mockFiles/swagger/disabled-rules.yml, test/spectral/mockFiles/swagger/enabled-rules.yml, test/spectral/tests/disabled-rules.test.js, test/spectral/tests/enabled-rules.test.js, test/spectral/tests/spectral-config.test.js, test/spectral/tests/spectral-validator.test.js
Purpose:
- Simplify the validator ruleset by using an equivalent Spectral rule
- Avoid resolving spec in-place to ensure inCodeValidator does not modify user's original spec object
Changes:
- Enable the operation-parameters Spectral rule
- Remove the in-code validation for parameters with duplicate `in:` and `name:` properties
- Pass a copy of the original spec to the reference resolver to prevent modification of the original spec
Tests:
- Remove tests meant to ensure the operation-parameters test is disabled
- Remove invalid oas3 from `disable-rules.yml` meant to invoke operation-parameters errors
- Remove irrelevant tests for in-code validation
- Add test to ensure operation-parameters check catches duplicate parameters for oas3 document
=> refactor: use Spectral to check for duplicate parameters

src/plugins/validation/2and3/semantic-validators/paths.js, src/spectral/rulesets/.defaultsForSpectral.yaml, test/plugins/validation/2and3/paths.test.js, test/spectral/mockFiles/oas3/disabled-rules.yml, test/spectral/mockFiles/swagger/disabled-rules.yml, test/spectral/tests/disabled-rules.test.js
Purpose:
- Simplify validator ruleset by using equivalent Spectral rule
Changes:
- Enable the path-not-include-query Spectral rule
- Remove the in-code validation for query string in paths
Tests:
- Remove irrelevant tests that ensure path-not-include-query Spectral rule disabled
- Remove irrelevant tests for in-code validation of in-path query strings
- Note: did not add enabled-rules test for path-not-include-query rule. Adding a query string to a path in the `enabled-rules.yml` test file also violates the validator's in-code paths_case_convention rule. This caused test failures that I thought would be ugly to fix, so thus far, we do not add a positive test for the path-not-include-query rule on our side.
=> refactor: use Spectral to check for query string in path

src/cli-validator/utils/circular-references-ibm.js, test/cli-validator/mockFiles/composite-pattern.yaml, test/cli-validator/tests/circular-refs-validator.test.js
A regression was recently introduced to the validator in the circular references
utility that prevented such references from being caught and sanitized. This resulted
in "call stack exceeded" exceptions for certain patterns using circular references.
The regression came in the form of checking for only "plain" objects, rather than
all "objects" (which include arrays). This happened in a recent community PR and I
didn't realize the consequences when I reviewed and merged. I went back and double
checked every instance of this change in that PR and believe this is the only one
that is problematic. I fixed it and added a new test case that would've caught this
regression had it been there.
Resolves #251
=> fix: properly handle circular regressions to prevent call stack exceptions

README.md
Adds the enabled rules from recent work, #248 and #249, to the README.
=> docs: add enabled Spectral rules to README

package-lock.json, package.json, src/cli-validator/utils/printJsonResults.js, src/lib/utils/printForMachine.js, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/info-and-hint.test.js, test/cli-validator/tests/option-handling.test.js, test/spectral/tests/enabled-rules.test.js
Changes:
- Get the validator version from `package.json` and include it in the json output
- Update `package.json` and `package-lock.json` to resolve differences in Spectral versions now
Tests:
- Update tests to match latest Spectral behavior
=> feat: include the validator version in the JSON output

src/plugins/utils/isPrimitiveType.js, src/plugins/validation/2and3/semantic-validators/responses.js, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/info-and-hint.test.js, test/cli-validator/tests/option-handling.test.js, test/plugins/utils/isPrimitiveType.test.js, test/plugins/validation/2and3/responses.test.js
Purpose:
- generator flattens reference to an array schema back into an inline schema
Changes:
- Add a check to see if the schema is an array with an items field that uses a ref or a primitive type (boolean, integer, number, string)
- Note: this update is only for response schemas. I looked through the different semantic validators and only found the `inline_response_schema` check. I did not find an equivalent check for inline request bodies.
Tests:
- Add tests to ensure the validator does not flag different variations of this array schema
- Update expected warnings in tests that use specs with this array schema
=> fix: no error for inline array schema when items field is a ref

appscan-config.xml
This issue excludes the README file from the ASOC codescanning system, which is flagging the Docker command instructions as security vulnerabilities.
=> chore: update appscan config

src/cli-validator/index.js, src/cli-validator/utils/checkVersion.js
Purpose:
- Node 8 reach its end-of-life, and Node 10 is scheduled to reach end of life at the end of April 2021.
Changes:
- Increase the required version.
- Change the check and deprecation message to warn for Node 10.x.
=> build: drop support for Node 8.x and deprecate Node 10.x

README.md, docs/spectral-rules.md, src/spectral/rulesets/.defaultsForSpectral.yaml, test/spectral/tests/custom-rules/content-entry-contains-schema.test.js, test/spectral/tests/spectral-config.test.js, test/spectral/tests/spectral-validator.test.js
Purpose:
- Establish a pattern in the validator for adding custom spectral rules and custom spectral functions
- Ensure content objects contain a schema
Changes:
- Add custom spectral rule to ensure that content objects contain a schema
- Add directory to store custom spectral rules and functions
- Add code to retrieve and merge custom spectral rules
Tests:
- Add tests for each use case outlined in the spectral rule
=> feat: custom Spectral rule to ensure content objects contain schema

src/cli-validator/index.js
Changes:
- Node version requires all three major, minor, patch fields, so update minimum version from 10.0 to 10.0.0
=> fix: correct the minimum required version of Node

docs/spectral-rules.md, src/spectral/rulesets/.defaultsForSpectral.yaml, src/spectral/rulesets/ibm-oas/response-example-provided.js, src/spectral/utils/spectral-validator.js, test/cli-validator/mockFiles/oas3/clean.yml, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/info-and-hint.test.js, test/spectral/mockFiles/oas3/disabled-rules.yml, test/spectral/tests/custom-rules/json-response-example-provided.test.js, test/spectral/tests/spectral-config.test.js, test/spectral/tests/spectral-validator.test.js
Purpose:
- Establish working pattern for writing custom functions such that, when users extend the `ibm:oas` ruleset, our custom functions are still findable by Spectral.
- Tooling to generate documentation relies on response examples provided either in the schema or "next to" the schema at response level. Warn about responses that do not provide examples in these locations.
Changes:
- Create a custom Spectral rule to warn about missing response examples
- Create a custom Spectral function to check if a response example provided in the locations supported by the code that generates documentation.
Tests:
- Add tests to ensure no warning given when a response example is provided.
- Add a test to ensure a warning is given when no response example provided.
Docs:
- Document the …
=> feat: warn for missing response examples

src/plugins/validation/2and3/semantic-validators/paths.js, test/plugins/validation/2and3/paths.test.js
We could implement the check for partial path templating as a configurable Spectral rule. This rule, however, will need a custom Spectral function. The initial work for adding a custom Spectral function is on hold until we determine how to ensure that users can extend our ruleset without having problems locating our custom functions. Should we resolve the custom functions problem and implement this check as a Spectral rule, or should we move this work through and remove the check?
Purpose:
- Partial path templating is not disallowed in OAS3, so although partial path templating may not be ideal style, do not want it to be an error.
Changes:
- Remove code that checks for partial path templating.
Tests:
- Remove tests that test partial path template validation code.
=> feat: remove error for partial path templating

docs/spectral-rules.md, src/cli-validator/runValidator.js, src/cli-validator/utils/noDeduplication.js, src/lib/index.js, src/spectral/rulesets/.defaultsForSpectral.yaml, src/spectral/rulesets/ibm-oas/error-response-schema.js, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/info-and-hint.test.js, test/spectral/mockFiles/oas3/disabled-rules.yml, test/spectral/tests/custom-rules/content-entry-contains-schema.test.js, test/spectral/tests/custom-rules/content-entry-provided.test.js, test/spectral/tests/custom-rules/error-response-schema.test.js, test/spectral/tests/custom-rules/error-response.test.js, test/spectral/tests/custom-rules/json-response-example-provided.test.js, test/spectral/tests/spectral-config.test.js, test/spectral/tests/spectral-validator.test.js
Purpose:
- Error responses should be robust and give the user enough information to resolve their problems. The added validation recommends certain fields be included and recommends a schema for those fields.
Changes:
- Add a custom Spectral rule that applies a custom Spectral function to validate 4xx and 5xx responses.
- Add a custom Spectral rule that validates the error response schema is an object, has fields, such as `trace`, `code`, `errors` or `error`, etc. and validates the schema of those fields to ensure the error response follows good practices.
- Defines a deduplication function and passes it to spectral to avoid deduplicating `response-error-response-schema` errors with the same path.
- Add a custom Spectral rule to check for `content` object in request bodies and non-204 …
=> Error responses

src/cli-validator/runValidator.js, src/cli-validator/utils/printResults.js, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/threshold-validator.test.js, test/spectral/tests/spectral-config.test.js
Purpose:
- Want the exit code set properly for json output.
Changes:
- Move the logic to set the exit code so that it applies to json output as well.
- If the warnings limit exceeded, add this as an error to the results so that it may be naturally included in the json output.
Tests:
- repair warnings limit tests and exit code tests
=> fix: set the exit code for json output

src/spectral/rulesets/.defaultsForSpectral.yaml, test/spectral/tests/custom-rules/response-example-provided.test.js
Purpose:
- Do not necessarily expect response examples for non-2xx and default responses. Expected for 2xx responses.
Changes:
- Soften the check to look only at success responses.
Tests:
- Update tests to ensure errors only issued for success responses without examples.
=> fix: soften the response-example rule to look only at success responses

src/cli-validator/runValidator.js, src/cli-validator/utils/addPathsToComponents.js, src/cli-validator/utils/getPathAsArray.js, src/cli-validator/utils/jsonResults.js, src/cli-validator/utils/printResults.js, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/utils/addPathsToComponents.test.js
Purpose:
- Errors may be scattered throughout a resolved schema, so we want to make it easy for users to identify the source component from which the error originates.
Changes:
- Walk the unresolved spec to see if the error occurs in a ref. Identify the source location and include the path to the component if the validator is in verbose mode.
- Update the `printRuleNames` variable to be `verbose` to be more general.
Tests:
- Add tests to ensure the path to the components added correctly.
=> feat: show path to component that caused error in verbose mode

docs/spectral-rules.md, src/spectral/rulesets/.defaultsForSpectral.yaml, src/spectral/rulesets/ibm-oas/check-major-version.js, test/cli-validator/tests/expected-output.test.js, test/spectral/mockFiles/oas3/multiple-major-versions.yml, test/spectral/tests/custom-rules/major-version-in-path.test.js, test/spectral/tests/enabled-rules.test.js, test/spectral/tests/spectral-config.test.js, test/spectral/tests/spectral-validator.test.js
This PR adds a new rule, `major-version-in-path`, the verifies that all paths contain a path segment that represents the major version of the API, in the form `v<n>`.  This is a requirement of the [IBM API Guidelines](https://cloud.ibm.com/docs/api-handbook?topic=api-handbook-uris#version).
Testing notes:
- Single major version specified in single server URL:
- test/cli-validator/mockFiles/oas3/clean.yml
- Single major version specified in multiple server URLs: no test
- Multiple major versions specified in multiple server URLs: inline in enabled-rules.js
- Single major version specified in basePath:
- test/cli-validator/mockFiles/swagger/clean.yml
- No major version in server URLs or paths
- oas2: test/spectral/mockFiles/swagger/enabled-rules.yml
- oas3: …
=> Add rule to check for consistent major version in path

src/plugins/utils/mergeAllOfSchemaProperties.js, src/plugins/validation/oas3/semantic-validators/pagination-ibm.js, test/plugins/utils/mergeAllOfSchemaProperties.test.js, test/plugins/validation/oas3/pagination-ibm.test.js
Purpose:
- When validating pagination, validator produces a false positive when the limit and offset properties are included in an allOf combined schema, and this fix resolves the bug.
Changes:
- Merges `allOf` schemas and top-level schema. Allows validation to be done as if one schema provided.
Tests:
- Ensure no errors occur when limit and offset are provided in allOf schema.
=> fix: when `limit` and `offset` properties included in `allOf`

docs/spectral-rules.md, src/spectral/rulesets/.defaultsForSpectral.yaml, test/spectral/tests/custom-rules/ibm-content-type-is-specific.test.js, test/spectral/tests/custom-rules/ibm-error-content-type-is-json.test.js
Purpose:
- Identify cases where the content type should be more specific or should likely just be application/json to ensure API and API definition are following good design principles.
Changes:
- Add Spectral rule to warn on any occurrence of `*/*` content-type
- Add Spectral rule to warn when error response content type does not support `application/json` because the error response is highly likely just be `application/json`
Tests:
- Add test specs for each that include both good practices and violations and ensure the proper number of errors occur
Docs:
- Document each rule
=> feat: warn for invalid content types

docs/spectral-rules.md, src/spectral/rulesets/.defaultsForSpectral.yaml, src/spectral/rulesets/schemas/x-sdk-operations.json, src/spectral/utils/spectral-validator.js, test/spectral/tests/custom-rules/ibm-sdk-operations.test.js
**Description:** 
- This PR uses a provided Spectral function to do JSON Schema validation. This is a positive because it is a well-defined way to invoke the AJV validator.
- The one drawback is that we need to dynamically convert the relative path to an absolute path before loading the default config into STATIC_ASSETS because we need to ensure Spectral can always find the schema regardless of the current working directory.
- The Spectral `schema` function has the same problem we observed (in Spectral `5.8.1` and below) in the `oas3-schema` rule where only one error is returned at a time. We will want to follow up on this implementation by raising this issue to Spectral and fixing the `schema` function.
Purpose:
- Validate that the x-sdk-operations extension is used correctly.
Changes:
- …
=> feat: validate `x-sdk-operations` extension

src/plugins/validation/2and3/semantic-validators/walker-ibm.js, test/plugins/validation/2and3/walker-ibm.test.js
As described in the [docs](https://swagger.io/docs/specification/data-models/enums/) `null` values are allowed inside enums. This PR fixed the lint error when you have nullable enums.
=> fix: allow null values inside enum property.

README.md
By default the validator doesn't accept array request bodies but that fact is not documented. This will likely help devs navigate to the spectral rule config faster. :)
=> Update Readme.md to include "request-body-object" spectral rule.

src/plugins/validation/2and3/semantic-validators/paths-ibm.js
Right now, we assume that parameters will have all required properties. This results
in the code crashing ungracefully if the "in" property is missing. This PR corrects
that. Missing "in" properties are already caught by spectral if there aren't other
issues with the property.
Resolves #307
=> fix: don't crash when parameter is missing required "in" property

.travis.yml, src/spectral/rulesets/.defaultsForSpectral.yaml, src/spectral/rulesets/ibm-oas/string-boundary.js, test/cli-validator/mockFiles/oas3/clean.yml, test/cli-validator/mockFiles/oas3/testoneof.yaml, test/cli-validator/tests/expected-output.test.js, test/cli-validator/tests/info-and-hint.test.js, test/spectral/mockFiles/oas3/disabled-rules.yml, test/spectral/tests/custom-rules/string-boundary.test.js
Purpose: encourage users to define schemas with explicit boundaries for valid string input.
Enforces use of `pattern`, `minLength`, and `maxLength` on `parameter` and `requestBody` string schemas.
Exceptions:
- `enum` defined
=> feat: string schema should define enum or pattern, minLength, maxLength

src/spectral/rulesets/.defaultsForSpectral.yaml, test/spectral/tests/custom-rules/content-entry-provided.test.js
Fixes #298.
Do not warn for missing `content` field for `101` and `202` responses because these protocols do not require response bodies.
=> fix: 101 and 202 responses do not need content entries

src/spectral/rulesets/.defaultsForSpectral.yaml, test/spectral/tests/custom-rules/prohibit-sentence-style-summaries.test.js
This PR brings that when `summary` field has a trailing period,
an error will be displayed.
The following example will result a validation error.
```json
{
"openapi": "3.0.0",
"info": {
"version": "1.0.0",
"title": "Summary does not have trailing period"
},
"servers": {},
"paths": {
"createTrailingPeriod": {
"post": {
"operationId": "createTrailingPeriod",
"description": "creates trailing period",
"summary": "Adds trailing period."
}
}
}
}
```
=> feat: prohibit sentence style summaries

src/cli-validator/utils/circular-references-ibm.js, test/cli-validator/mockFiles/multi-file-spec/city.yaml, test/cli-validator/mockFiles/multi-file-spec/main.yaml, test/cli-validator/mockFiles/multi-file-spec/schema.yaml, test/cli-validator/mockFiles/multi-file-spec/sports-team.yaml, test/cli-validator/tests/circular-refs-validator.test.js
The validator chokes on a specific scenario - when a multi-file spec
has schemas that reference each other in a ciruclar manner across files.
The bundler we use to put together mutli-file specs doesn't store the
reference in a helpful way, so there's not really a way to report the
location of the circular reference the way we do for other scenarios.
All we can really do is avoid crashing completely and send the user the
fully resolved path to the problematic schema that they will need to
trace manually.
A test is added to capture the behavior. This test case would exhibit the
crash without the fix.
Resolves #326
=> fix: handle multi-file spec circular reference edge case

src/lib/index.js, test/cli-validator/tests/inCodeConfigFileOverride.test.js
Expands on #323.
Provides parameter for custom `configFileOverride` file.
Adds a test to ensure the `configFileOverride` is passed to `processConfiguration.get`.
=> feat: add configFileOverride to in-code validator

.cra/.cveignore, package-lock.json, package.json
This change uses the `npm-force-resolutions` package as a dev-dependency to up-version the pac-resolver dependency to 5.0.0 from 4.2.0. This is a workaround until Spectral is upgraded to 6.0.0.
I also added the vulnerability ignore for the ansi-regex dev-dependency so the Ad-hoc scan is clean.
=> fix: pac-resolver force dependency to 5.0.0

.travis.yml
Bumping this up from v12 as semantic release now recommends
running with v14.
=> build: run release script on node v14

README.md
=> Add missing quotes around @ibm-cloud/openapi-ruleset in the README

packages/ruleset/src/rules/string-boundary.js, packages/ruleset/test/string-boundary.test.js
Currently, the custom string-boundary rule only validates parameters
defined at the operation level and request body properties. However,
parameters can also be defined at the path level. This commit adds
that scenario to the rule.
Resolves #352 
FYI @meem
=> fix(string-boundary): include parameters defined at path level

.cra/.cveignore
Snyk vulnerability `SNYK-JS-LODASHSET-1320032` should be ignored until spectral approves fix mentioned here: https://github.com/stoplightio/spectral/issues/2017
=> fix: omit lodash.set vuln until spectral approves fix

.secrets.baseline, package-lock.json, packages/validator/src/cli-validator/run-validator.js, packages/validator/src/cli-validator/utils/custom-deduplication.js, packages/validator/src/cli-validator/utils/no-deduplication.js, packages/validator/src/spectral/spectral-validator.js, packages/validator/test/cli-validator/mock-files/oas3/component-path-example.yaml, packages/validator/test/cli-validator/tests/expected-output.test.js, packages/validator/test/cli-validator/tests/info-and-hint.test.js
This commit updates the format in which we provide the document data to spectral,
which in turns allows end users to take advantage of spectral "overrides". This
feature allows users to ignore specific parts of their document if they need,
rather than turning off entire rules.
In doing this, we give spectral greater control over the validations it returns.
This allows us to take advantage of another spectral feature - automatically
resolving component paths. Before, if a schema contained a problem and two references
pointed to it, some rules would return two validations pointing to the reference
instances. Now, the validation returns one validation, pointing to the base schema.
This will result in some output changes for some users but it should be a positive
change overall.
This commit …
=> feat: enable spectral overrides

package-lock.json
This PR bumps our node-fetch transitive dependency to avoid a snyk vulnerability.
=> fix: bump node-fetch to avoid vulnerability

packages/validator/src/plugins/validation/2and3/semantic-validators/schema-ibm.js, packages/validator/test/cli-validator/mock-files/oas3/test-formats.yaml, packages/validator/test/cli-validator/mock-files/oas3/testoneof.yaml, packages/validator/test/plugins/validation/2and3/schema-ibm.test.js
This commit adds "crn", "email", "identifier", "url", and "uuid"
to the list of allowable format values for a string schema,
and adds a new test related to type/format pairs.
=> fix: add supported formats to invalid_type_format_pair rule

package-lock.json, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/schema-description.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/schema-description.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/path-matches-regexp.js, packages/ruleset/test/path-matches-regexp.test.js, packages/ruleset/test/schema-description.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/package.json, packages/validator/src/.defaultsForValidator.js, packages/validator/src/plugins/validation/2and3/semantic-validators/schema-ibm.js, packages/validator/test/cli-validator/mock-files/just-warn-config-override.json, packages/validator/test/cli-validator/tests/expected-output.test.js, packages/validator/test/cli-validator/tests/info-and-hint.test.js, packages/validator/test/cli-validator/tests/option-handling.test.js, packages/validator/test/plugins/validation/2and3/schema-ibm.test.js
This commit adds support for a new spectral-style rule
with id 'schema-description' and removes the old rules
'no_schema_description' and 'no_property_description'.
Also included are changes to tests in the validator package
to reflect the removal of those two rules.
=> feat: add 'schema-description' spectral rule and remove old rules

README.md, packages/ruleset/src/functions/description-mentions-json.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/description-mentions-json.js, packages/ruleset/src/rules/index.js, packages/ruleset/test/description-mentions-json.test.js, packages/validator/src/.defaultsForValidator.js, packages/validator/src/plugins/validation/2and3/semantic-validators/schema-ibm.js, packages/validator/test/plugins/validation/2and3/schema-ibm.test.js
This commit adds support for a new spectral-style rule
with id 'description-mentions-json' and removes the old rule
'description_mentions_json'.
Also included are changes to tests in the validator package
to reflect the removal of the old rule.
=> feat: add 'description-mentions-json' spectral rule and remove old rule

packages/validator/src/cli-validator/run-validator.js
This commit makes a small change to our exception handling
so that if spectral returns a "Error running Nimma" exception,
we'll print out the details of the exception even if debug is
not currently enabled.
=> fix: display details for 'Error running Nimma' errors

package-lock.json
This PR just bumps up our version of urijs in order to avoid the SNYK-JS-URIJS-2401466 vulnerability.
Note: in order to submit this change, I ran the following commands:
```
npm run clean
rm package-lock.json
npm install
```
This resulted in the 1.19.8 version of urijs being brought in and the package-lock.json file was updated accordingly.   Previously, the 1.19.7 version of urijs was being used.
=> chore: bump urijs to resolve vulnerability

packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/property-description.js, packages/ruleset/src/functions/schema-description.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/property-description.js, packages/ruleset/test/property-description.test.js, packages/ruleset/test/schema-description.test.js, packages/validator/src/.defaultsForValidator.js
A recent change was made that converted the old
'no_property_description' and 'no_schema_description' rules
into a single new 'schema-description' Spectral-style rule.
This commit introduces a new 'property-description' rule
and removes the property-related checks from the
'schema-description' rule.
So now, 'schema-description' will specifically ensure that
schemas have a non-empty description, while the new
'property-description' rule will ensure that
schema properties have a non-empty description.
This change is being made so that each rule can be
enabled/disabled separately according to user requirements.
=> feat(property-description): add new 'property-description' rule

README.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/parameter-default.js, packages/ruleset/src/functions/parameter-description.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/parameter-default.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/is-sdk-excluded.js, packages/ruleset/test/parameter-default.test.js, packages/ruleset/test/utils/test-rule.js, packages/validator/src/.defaultsForValidator.js, packages/validator/src/plugins/validation/2and3/semantic-validators/parameters-ibm.js, packages/validator/test/plugins/validation/2and3/parameters-ibm.test.js
This commit converts the old 'required_param_has_default' rule
into a new Spectral-style rule 'parameter-default'.
Disregard the oldest commit because this PR is stacked up behind my previous PR re: the parameter-description rule.  Once that PR is merged, I'll rebase this one.
=> feat: add new 'parameter-default' rule and remove old rule

docs/ibm-legacy-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/parameter-case-convention.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/parameter-case-convention.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/is-deprecated.js, packages/ruleset/test/parameter-case-convention.test.js, packages/validator/src/.defaultsForValidator.js
This commit converts the old 'param_name_case_convention' rule
into a new Spectral-style rule 'parameter-case-convention'.
=> feat(parameter-case-convention): add new 'parameter-case-convention' rule and remove old rule

packages/validator/src/.defaultsForValidator.js
This PR just fixes a typo "Sectral" vs "Spectral" :)
=> chore: fix typo in .defaultsForValidator.js

.secrets.baseline, packages/ruleset/src/functions/pagination-style.js, packages/ruleset/test/pagination-style.test.js
This PR fixes a bug in the pagination-style rule that would occur when a list-type operation appears to support a paginated response schema, but yet the operation had no parameters at all.
=> fix(pagination-style): fix bug in pagination-style rule

package-lock.json
This PR bumps our version of minimist to 1.2.6 to avoid a vulnerability
=> build: bump minimist to 1.2.6 to avoid vulnerability

packages/ruleset/src/functions/check-major-version.js, packages/ruleset/test/major-version-in-path.test.js
This PR modifies the checkMajorVersion function so that:
1. it now attempts to resolve a parameterized server.url value using the default values of the server entry's variables.
2. it tolerates a malformed URL string by catching and absorbing any exception that might get thrown while parsing the server.url value. 
=> fix(major-version-in-path): tolerate invalid server.url value

README.md
This section focused on the legacy format and included some broken links.
This commit redirects the reader to the appropriate documentation.
=> docs: update outdated customization section in README

packages/ruleset/src/functions/string-boundary.js, packages/ruleset/src/rules/string-boundary.js, packages/ruleset/test/string-boundary.test.js, packages/ruleset/test/utils/root-document.js
This commit updates the string-boundary rule slightly to be a bit
more accurate in terms of the warnings that are issued for
string properties with various format values specified for them.
=> fix(string-boundary): update string-boundary rule with new formats

docs/ibm-cloud-rules.md, docs/ibm-legacy-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/request-body-name.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/request-body-name.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/is-form-mimetype.js, packages/ruleset/src/utils/is-json-mimetype.js, packages/ruleset/test/is-form-mimetype.test.js, packages/ruleset/test/is-json-mimetype.test.js, packages/ruleset/test/request-body-name.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/src/.defaultsForValidator.js, packages/validator/src/plugins/validation/oas3/semantic-validators/operations.js, packages/validator/test/plugins/validation/oas3/operations.test.js
'request-body-name' rule, which replaces the
legacy 'no_request_body_name' rule.
=> feat(request-body-name): add new request-body-name rule

packages/ruleset/src/functions/array-of-arrays.js, packages/ruleset/src/functions/required-property.js, packages/ruleset/src/functions/string-boundary.js, packages/ruleset/src/utils/validate-subschemas.js, packages/ruleset/test/array-of-arrays.test.js, packages/ruleset/test/missing-required-property.test.js, packages/ruleset/test/string-boundary.test.js
We've been validating some constraints for `not` schemas that probably don't really apply in scenarios where a `not` schema would be used. This PR backs off validation of some rules from `not` schemas.
=>  Exclude inapplicable validation from `not` schemas

package-lock.json, packages/ruleset/src/functions/operation-id-naming-convention.js, packages/ruleset/test/binary-schemas.test.js, packages/ruleset/test/operation-id-naming-convention.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/test/cli-validator/mock-files/clean-with-tabs.yml, packages/validator/test/cli-validator/mock-files/clean.yml, packages/validator/test/cli-validator/tests/expected-output.test.js, packages/validator/test/cli-validator/tests/option-handling.test.js
This PR updates the `operation-id-naming-convention` rule so that it more closely tracks the current API Handbook guidance around operation id's.
=> fix(operation-id-naming-convention): update rule with latest guidance

packages/ruleset/src/functions/pagination-style.js, packages/ruleset/src/utils/merge-allof-schema-properties.js, packages/ruleset/test/merge-allof-schema-properties.test.js, packages/ruleset/test/pagination-style.test.js, packages/validator/test/cli-validator/tests/expected-output.test.js
This commit fixes two issues in the 'pagination-style' rule:
1. The "previous" and "last" properties are no longer required
to be defined in a paginated response schema.  This change
brings the rule more in sync with the API handbook guidance.
2. The rule previously did not correctly process an allOf list
while performing checks on the "first", "next", "previous" or
"last" response schema properties.  This is now fixed.
=> fix(pagination-style): fix issues in 'pagination-style' rule

docs/ibm-cloud-rules.md
Code flags `array-responses` violations as `error` yet it's documented as `warn`. This change aligns documentation with implementation.
Code: https://github.com/IBM/openapi-validator/blob/main/packages/ruleset/src/rules/array-responses.js#L10
=> Correct array-responses severity in documentation

.secrets.baseline, docs/ibm-cloud-rules.md, package-lock.json, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/property-inconsistent-name-and-type.js, packages/ruleset/src/functions/ref-sibling-duplicate-description.js, packages/ruleset/src/functions/schema-type.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/ref-sibling-duplicate-description.js, packages/ruleset/src/utils/get-schema-type.js, packages/ruleset/src/utils/merge-allof-schema-properties.js, packages/ruleset/test/merge-allof-schema-properties.test.js, packages/ruleset/test/ref-sibling-duplicate-description.test.js, packages/ruleset/test/schema-type.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/src/.defaultsForValidator.js
This commit introduces a new spectral-style
'ref-sibling-duplicate-description' validation rule that will
check for situations where a "ref-sibling" allOf pattern is used
unnecessarily to try to override a schema description, but the
overridden description is the same as the original description.
=> feat(ref-sibling-duplicate-description): add new spectral-style rule

package-lock.json, packages/validator/package.json
Avoid vulnerability in `got` sub-dependency due to Snyk vuln: SNYK-JS-GOT-2932019
Updating `update-notifier` to the latest version satisfies this change.
=> chore: bump update-notifier version to avoid got vulnerability

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/array-boundary.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/array-boundary.js, packages/ruleset/src/rules/index.js, packages/ruleset/test/array-boundary.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/test/cli-validator/mock-files/oas3/clean.yml, packages/validator/test/cli-validator/mock-files/oas3/component-path-example.yaml, packages/validator/test/cli-validator/mock-files/oas3/err-and-warn.yaml
Adds a new rule to enforce constraints are set on array schemas. This is to enforce [the related guidance in the API Handbook](https://cloud.ibm.com/docs/api-handbook?topic=api-handbook-types#array) and resolves #458.
One consideration is that the constraints are only required for request schemas and just recommended for response schemas. We could potentially only validate request schemas but the "SHOULD" in the handbook for response schemas seems enough motivation to me to add the warning. Happy to entertain other opinions on this. It is the kind of rule that may start adding lots of warnings in user's API Definitions.
=> New rule/array constraints

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/response-status-codes.js, packages/ruleset/test/response-status-codes.test.js, packages/validator/test/cli-validator/mock-files/oas3/clean.yml, packages/validator/test/cli-validator/tests/expected-output.test.js
This commit updates the 'response-status-codes' rule so that it will
now check to make sure that an operation whose operationId starts with
the word "create" is returning a '201 - Created' status code.
=> fix(response-status-codes): add check for 201 response on 'create' operation

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/delete-body.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/delete-body.js, packages/ruleset/src/rules/index.js, packages/ruleset/test/delete-body.test.js
This commit adds a new spectral-style rule with id 'delete-body',
which will warn about any "delete" operations that contain
a requestBody field.
=> feat(delete-body): add new spectral-style 'delete-body' rule

package-lock.json, packages/ruleset/package.json, packages/validator/package.json, packages/validator/test/cli-validator/tests/expected-output.test.js, packages/validator/test/cli-validator/tests/option-handling.test.js
This resolves an issue in which users would see validations with
paths that did not point to the correct location in the API definition.
This was caused by a bug in Spectral that has now been fixed.
=> fix: update spectral version to resolve path mapping bug

packages/ruleset/src/functions/array-boundary.js, packages/ruleset/src/functions/property-description.js, packages/ruleset/src/functions/ref-sibling-duplicate-description.js, packages/ruleset/src/functions/schema-description.js, packages/ruleset/src/functions/schema-type.js, packages/ruleset/src/utils/validate-composed-schemas.js, packages/ruleset/src/utils/validate-nested-schemas.js, packages/ruleset/src/utils/validate-subschemas.js, packages/ruleset/test/validate-composed-schemas.test.js, packages/ruleset/test/validate-nested-schemas.test.js
When invoking a function on a rule with the resolved spec, it is prudent to
check for schemas defined by a $ref. In the resolved spec, schemas defined with
a $ref are the result of circular references being detected and it isn't
necessary to validate the schemas.
To avoid duplicating this check for each function and requiring manual
maintenance in all functions (many were missing the check), I moved it to the
validate functions that they all rely on to recursively check schemas.
The only potential downside here is that it would prevent us from writing a
function that recursively walks through the unresolved spec and that also
relies on the presence of $refs in the schemas. This feels extremely unlikely
to me so it seems a worthwhile optimization.
Happy to be corrected if I'm making a bad …
=> refactor: move $ref check out of individual functions

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/string-boundary.js, packages/ruleset/src/utils/get-composite-schema-attribute.js, packages/ruleset/src/utils/index.js, packages/ruleset/test/get-composite-schema-attribute.test.js, packages/ruleset/test/string-boundary.test.js
This commit modifies the "string-boundary" rule so that it
more accurately performs the checks for the various schema
attributes within composed schemas.
For example, if a string schema contains an allOf, then the
"pattern" field could be specified in any of the allOf
list element schemas instead of the main schema itself.
In contrast, for a string schema containing a oneOf or anyOf,
the "pattern" field would need to be specified in either
the main schema itself OR within EACH of the oneOf/anyOf
list element schemas.
Previously, the rule was not accurate enough with its
checks within composed schemas.
=> fix(string-boundary): improve handling of composed schemas

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/consecutive-path-param-segments.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/path-segment-case-convention.js, packages/ruleset/src/functions/valid-path-segments.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/consecutive-path-param-segments.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/valid-path-segments.js, packages/ruleset/test/consecutive-path-param-segments.test.js, packages/ruleset/test/valid-path-segments.test.js
This commit introduces the following new spectral-style rules:
1. consecutive-path-param-segments: detects presence of
two or more consecutive path segments containing param
references within a path string.
2. valid-path-segments: checks path segments within each
path string to ensure parameter references are well-formed.
=> feat: add 2 new rules related to path segments

packages/ruleset/src/functions/security-scheme-attributes.js, packages/ruleset/test/security-scheme-attributes.test.js
The OpenAPI specification [allows for relative references](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#relativeReferences) in URL properties
throughout an API document. We were not considering this in the
`security-scheme-attributes` rule. This commit adjusts the logic to allow
for relative URLs.
Resolves #466
=> fix: allow relative urls in security schemes

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-etag-header.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/no-etag-header.js, packages/ruleset/test/array-items.test.js, packages/ruleset/test/array-of-arrays.test.js, packages/ruleset/test/description-mentions-json.test.js, packages/ruleset/test/no-etag-header.test.js, packages/ruleset/test/property-case-collision.test.js, packages/ruleset/test/property-description.test.js, packages/ruleset/test/security-schemes.test.js, packages/ruleset/test/utils/root-document.js, packages/ruleset/test/valid-type-format.test.js
This commit introduces a new spectral-style rule with
id 'no-etag-header'.  This rule will check to make sure that
a path's GET operation defines the ETag response
header if any of the path's operations support header parameters
named If-Match or If-None-Match.
=> feat(no-etag-header): add new 'no-etag-header' spectral-style rule

docs/ibm-cloud-rules.md, packages/ruleset/src/rules/property-inconsistent-name-and-type.js, packages/ruleset/test/property-inconsistent-name-and-type.test.js
This commit modifies the 'property-inconsistent-name-and-type' rule configuration
so that it is disabled by default.
=> feat(property-inconsistent-name-and-type): disable rule in default configuration

docs/ibm-cloud-rules.md, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/if-modified-since-parameter.js, packages/ruleset/src/rules/if-unmodified-since-parameter.js, packages/ruleset/src/rules/index.js, packages/ruleset/test/if-modified-since-parameter.test.js, packages/ruleset/test/if-unmodified-since-parameter.test.js
This commit introduces two new rules that warn about the use of
specific header parameters that are discouraged by the API Handbook:
1. if-modified-since-parameter - warns about operations that support the
If-Modified-Since header parameter.
2. if-unmodified-since-parameter - warns about operations that support the
If-Unmodified-Since header parameter.
=> feat: add new rules 'if-modified-since-parameter' and if-unmodified-since-parameter

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/error-response-schema.js, packages/ruleset/src/rules/response-error-response-schema.js, packages/ruleset/test/array-boundary.test.js, packages/ruleset/test/description-mentions-json.test.js, packages/ruleset/test/inline-response-schema.test.js, packages/ruleset/test/property-description.test.js, packages/ruleset/test/response-error-response-schema.test.js, packages/ruleset/test/schema-description.test.js, packages/ruleset/test/schema-type.test.js, packages/ruleset/test/utils/root-document.js
This commit updates the implementation, tests and documentation
associated with the 'response-error-response-schema' validation rule
so that it more accurately implements the API Handbook guidance
related to error response schemas.
=> fix(response-error-response-schema): bring rule in sync with API Handbook

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/request-body-name.js, packages/ruleset/test/utils/root-document.js
This commit updates the 'request-body-name' rule so that it supports
patch operations with requestBody mimetypes `application/json-patch+json` 
and `application/merge-patch+json` and treats those the same as normal
operations with a normal json-based request body.
=> fix(request-body-name): support json-patch/merge-patch operations

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/response-status-codes.js, packages/ruleset/test/response-status-codes.test.js, packages/validator/test/cli-validator/tests/expected-output.test.js
This commit fixes a problem with the 'response-status-codes'
validation rule.  Prior to this change, any POST request would be considered
a "create" operation.  Now, a POST request will be considered a
"create" operation only if the API also defines a corresponding
get/put/patch/delete path (i.e. a similar path but with a trailing
path param reference.
In any case, an operation whose operationId starts with "create"
will continue to be considered a "create" operation regardless of the
paths defined in the API.
=> fix(response-status-codes): avoid false positives for 'create' operations

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/optional-request-body.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/optional-request-body.js, packages/ruleset/test/optional-request-body.test.js, packages/ruleset/test/utils/root-document.js
This commit introduces a new spectral-style
'optional-request-body' rule, which will examine
each optional request body and it's associated schema
to see if it looks like the API author might have
intended to define the requestBody as required.
It is rare to have an optional requestBody with
a schema that contains required properties.
=> feat(optional-request-body): add new spectral-style rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/merge-patch-optional-properties.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/merge-patch-optional-properties.js, packages/ruleset/test/merge-patch-optional-properties.test.js, packages/ruleset/test/optional-request-body.test.js, packages/ruleset/test/property-attributes.test.js, packages/ruleset/test/utils/root-document.js
'merge-patch-optional-properties' rule which will verify that
the requestBody schemas for "merge-patch" type operations do not
contain any required properties and do not specify a non-zero
value for the "minProperties" field.
=> feat(merge-patch-optional-properties): add new spectral-style rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/collection-array-property.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/pagination-style.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/collection-array-property.js, packages/ruleset/src/rules/index.js, packages/ruleset/test/collection-array-property.test.js, packages/ruleset/test/pagination-style.test.js, packages/validator/test/cli-validator/tests/expected-output.test.js
'collection-array-property' rule, which will
verify that each "list" type operation has a response
schema that defines an array property named after the
plural form of the resource type.
=> feat(collection-array-property): add new spectral-style rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/path-param-not-crn.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/path-param-not-crn.js, packages/ruleset/test/path-param-not-crn.test.js
'path-param-not-crn' validation rule which will verify that there are no path parameters that are defined as a CRN (Cloud Resource Name) value.
=> feat(path-param-not-crn): add new spectral-style rule

.releaserc, .travis.yml, package.json, packages/validator/package.json, scripts/create-binaries.sh
The pkg script was broken because of some clever usage of "rename" that wasn't compatible with all devices. This commit removes the need for it by moving the logic into a separate bash script with way more clarity.
This also updates semantic release to include the built platform binaries in the "assets" section of the release on GitHub.
=> fix: fix broken pkg script and publish binaries to github

.travis.yml, packages/validator/src/cli-validator/index.js, packages/validator/src/cli-validator/utils/get-version-string.js
This commit adds the ruleset verion number to the `--version` output so it is easier for the user to link their current version to the updates in the changelog, etc.
This also makes a modification to allow for publishing of binaries to the GitHub release.
Example output:
```
$ node packages/validator/src/cli-validator/index.js --version
validator: 0.95.1; ruleset: 0.44.0
```
Resolves #498
=> feat: add ruleset version string to `--version` output

README.md
Now that we're building binary files and publishing them to the release assets, we should point to them from the README file. This commit adds documentation for them and updates the existing documentation on building binaries from source code.
=> docs: add documentation for downloadable binary files

README.md
```
$ npx lint-openapi
Usage: lint-openapi [options] [<file>]
Run the validator on a specified file
Options:
-c, --config <file>            path to config file, used instead of .validaterc if provided
-d, --default_mode             ignore config file and run in default mode
-e, --errors_only              only print the errors, ignore the warnings
-j, --json                     output as json
-n, --no_colors                turn off output coloring
-p, --print_validator_modules  print the validators that catch each error/warning (helpful for development)
-r, --ruleset <file>           path to Spectral ruleset file, used instead of .spectral.yaml if provided
-s, --report_statistics        report the frequency of each occurring error/warning
-v, --verbose                  increase the …
```
=> There's no [command] option in CLI

packages/ruleset/src/rules/content-entry-contains-schema.js, packages/ruleset/src/rules/optional-request-body.js, packages/ruleset/src/rules/request-body-object.js, packages/ruleset/test/meta/rule-style.test.js
I'm wary of proclaiming that this definitely fixes our recent performance issues since @dpopp07 saw some really unpredictable behavior that seemed unrelated to this specific rule. But, I did profile the validator with `node --prof` and, in the resulting log, a fragment of this JSON path expression was being executed hundreds of times for an extremely simple API definition and millions of times for a complex definition.
It bothers me that I can't figure out exactly what a `.[*]` construct is **supposed** to do in JSON path, but in practice, it seems to result in some sort of recursion (maybe it's a synonym for `..`?). I'm guessing that the three instances meant it was `O(n^3)` or something.
In any case, the update didn't cause any test failures and did seem to resolve the performance …
=> perf: remove accidental recursion in given statements

packages/ruleset/test/meta/spectral-depedencies.test.js
Add a test for the assumption that when Spectral resolves a schema, two identical `$ref` references will result in the same (`===` equivalent) in-memory object.
=> test: Spectal assumption for resolved reference equivalence

packages/ruleset/src/functions/collection-array-property.js
If a path object does not have a "get" operation, the code would previously pass `undefined` to a function that tried to access properties of the given operation object. This would result in an exception that would crash the underlying nimma parser.
This commit simply adds a check for truthyness before continuing with the function.
=> fix(collection-array-property): avoid bug that crashes nimma

packages/validator/src/cli-validator/run-validator.js, packages/validator/test/cli-validator/tests/error-handling.test.js
Signed-off-by: Dan Hudlow <dhudlow@us.ibm.com>
The feature to remove trailing commas (which are _not valid_ in JSON) mangled properties containing regular expressions such as `"pattern": "^[-0-9a-zA-Z_,]+$"` within an OpenAPI definition.
IMO, we should simply require valid JSON documents.
=> fix: remove buggy support for tolerating trailing commas

docs/ibm-cloud-rules.md
This PR modifies the rule reference docs to make sure that each rule's reference section has a tag equal to the rule-id.  This is being done because spectral computes the "documentationUrl" value for each rule by appending `#<rule-id>` to the documentationUrl value specified in our rule file (ibm-oas.js).
=> docs: fix rule doc tags to match documentationUrl

.releaserc, package.json, packages/ruleset/package.json, packages/validator/CHANGELOG.md, packages/validator/package.json, scripts/create-binaries.sh
This PR adjusts the "pkg" command so that it is ultimately run only in
the validator package.
=> fix: create executables in correct package

packages/ruleset/src/functions/property-case-convention.js, packages/ruleset/test/property-case-convention.test.js, packages/validator/test/cli-validator/tests/expected-output.test.js
This commit modifies the "property-case-convention" rule slightly so that when it reports a problem with the case for a specific property, the offending property name will be included in the error message, and the path associated with the error will reflect the schema's "properties" field in which the offending property is defined.
This subtle change will ensure that the spectral "unresolver" will not be overzealous when "unresolving" the path.
Background info on this PR can be found in the [issue](https://github.ibm.com/arf/planning-sdk-squad/issues/3485)
=> fix(property-case-convention): report correct path in errors

package-lock.json, packages/ruleset/package.json, packages/validator/package.json
The `validator` dependency is only used in the ruleset package but was still living in the `package.json` for the validator package. This was likely an oversight during the re-architecture into a monorepo. This resolves the issue by moving the dependency to the correct `package.json`.
Resolves #528
=> fix: move `validator` dependency to correct package within monorepo

packages/ruleset/package.json, packages/ruleset/src/ibm-oas.js
Signed-off-by: Dan Hudlow <dhudlow@us.ibm.com>
Adjusts `prettier` config to favor consistent property quoting.
=> fix: update lint config to make property quoting consistent

packages/ruleset/src/functions/ref-pattern.js
This commit fixes a regex pattern in the `ref-pattern` rule.
When an operation path contained a specific OpenAPI field name
(e.g. `properties`) the old regex pattern could match and it resulted
in a false positive warning.
The cause of the issue was missing parentheses around the "main"
pattern which made the first comma "optional" due to the OR operators.
(Actually it was only required for the `schema`.)
```yaml
/tekton_pipelines/{pipeline_id}/properties:
parameters:
- $ref: '#/components/parameters/pipelineId'
```
Before:
After:
Closes: #489 
Signed-off-by: Norbert Biczo <pyrooka@users.noreply.github.com>
=> fix(ref-pattern): better regex matching if path contains OpenAPI field name

.secrets.baseline, README.md, package-lock.json, package.json, packages/ruleset/package.json, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/logger-factory.js, packages/ruleset/test/logger-factory.test.js, packages/validator/package.json, packages/validator/src/cli-validator/index.js, packages/validator/src/cli-validator/run-validator.js, packages/validator/src/cli-validator/utils/json-results.js, packages/validator/src/cli-validator/utils/print-results.js, packages/validator/src/cli-validator/utils/validator.js, packages/validator/src/lib/index.js, packages/validator/src/spectral/spectral-validator.js, packages/validator/test/cli-validator/tests/config-file-validator.test.js, packages/validator/test/cli-validator/tests/error-handling.test.js, packages/validator/test/cli-validator/tests/expected-output.test.js, packages/validator/test/cli-validator/tests/option-handling.test.js, packages/validator/test/cli-validator/tests/threshold-validator.test.js
This commit adds logging support to the validator. The validator core itself will use a "root" logger, and each validation rule will have its own logger with a name equal to its rule name (e.g. ibm-schema-description). The user can set the logging levels with the
-l/--loglevel command-line options.
Note that this PR only includes the changes to the validator core.  Changes to individual rules to support debug logging will be done as we update each rule.
=> feat(logger): add logger facility to validator core

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/array-of-arrays.js, packages/ruleset/src/functions/array-responses.js, packages/ruleset/src/functions/binary-schemas.js, packages/ruleset/src/functions/circular-refs.js, packages/ruleset/src/functions/collection-array-property.js, packages/ruleset/src/functions/consecutive-path-segments.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/collection-array-property.js, packages/ruleset/src/rules/consecutive-path-segments.js, packages/ruleset/src/rules/index.js, packages/ruleset/test/accept-parameter.test.js, packages/ruleset/test/array-attributes.test.js, packages/ruleset/test/array-of-arrays.test.js, packages/ruleset/test/array-responses.test.js, packages/ruleset/test/authorization-parameter.test.js, packages/ruleset/test/binary-schemas.test.js, packages/ruleset/test/circular-refs.test.js, packages/ruleset/test/collection-array-property.test.js, packages/ruleset/test/consecutive-path-segments.test.js
This commit covers the following rules:
- ibm-array-of-arrays
- ibm-array-responses
- ibm-binary-schemas
- ibm-circular-refs
- ibm-collection-array-property
- ibm-consecutive-path-segments
=> fix: refine validation rules as part of pre-1.0 work (group 2)

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/disallowed-header-parameter.js, packages/ruleset/src/rules/if-modified-since-parameter.js, packages/ruleset/src/rules/if-unmodified-since-parameter.js, packages/ruleset/test/if-modified-since-parameter.test.js, packages/ruleset/test/if-unmodified-since-parameter.test.js, packages/ruleset/test/inline-property-schema.test.js, packages/ruleset/test/inline-request-schema.test.js, packages/ruleset/test/inline-response-schema.test.js
This commit covers the following rules:
- ibm-if-modified-since-parameter
- ibm-if-unmodified-since-parameter
- ibm-inline-property-schema
- ibm-inline-request-schema
- ibm-inline-response-schema
=> fix: refine validation rules as part of pre-1.0 work (group 5)

packages/ruleset/src/utils/is-empty-object-schema.js, packages/ruleset/test/inline-property-schema.test.js, packages/ruleset/test/is-empty-object-schema.test.js
This commit modifies the isEmptyObjectSchema() utility function so that it will correctly ignore annotations present on a schema when deciding whether or not a schema is an "empty object" schema (i.e. an object schema with no properties defined).
=> fix(inline-property-schema): avoid false warnings

.releaserc
Adding a "branch" to our semantic release configuration will allow for automated releases off of our pre-release branch, so that we can start publishing release candidates with each new change that we make.
=> build: add pre-release config for semantic release

.travis.yml
Right now, the Travis file dictates that the deploy step will only be run for the `main` branch. However, the only command we run during the deploy step is to invoke semantic release. Semantic release also dictates that it will only run on certain branches, so it should be sufficient for controlling the conditional deployment.
We want to deploy on multiple branches in order to publish release candidates from our pre-release branch, so this commit enables Travis to run the deploy step on each branch and lets semantic release control which branches are actually deployed from.
=> build: use semantic release to control conditional deployment

.releaserc, .travis.yml
This reverts commit b064d2c2a2ef4fb8a57530efe8dc165e130ead3c and db0f88d44cdcd1429a36c5c01600ae916be87b37
The pre-release config didn't work out as planned - the "multi semantic release" package didn't handle the pre-release config as expected and I wasn't able to see a clear solution. Since we have more important things to do than debug the setup, I think we should revert the change to publish on all branches and handle release candidates manually.
=> Revert "build: use semantic release to control conditional deployment (#562)"

packages/validator/src/cli-validator/run-validator.js, packages/validator/src/cli-validator/utils/get-path-as-array.js, packages/validator/src/cli-validator/utils/print-results.js, packages/validator/test/cli-validator/tests/threshold-validator.test.js
Currently, we loop through all validations and check if "summary only" is enabled before we print them. It would be more efficient and readable to check once at the beginning, printing the summary and exiting if the feature is enabled.
This commit also includes some other, minor refactoring.
=> refactor: optimize logic for summary-only feature

package-lock.json, packages/ruleset/package.json, packages/utilities/package.json, packages/validator/package.json
Node v14 will be sunset [very soon](https://endoflife.date/nodejs). We should take the v1 opportunity to bump our minimum version to v16.
BREAKING CHANGE: Node v16 is now the minimum supported version of Node for running this tool.
=> build: require node v16 as minimum version

Migration-Guide.md, packages/validator/src/cli-validator/run-validator.js
Add a couple of strategic newlines for better presentation in the CLI and add information to the Migration Guide indicating the move up to Node engine v16.
I found these newlines to make the output more clear while preparing to give a demo on the tool during our playback.
=> chore: final edits and migration info for 1.0

.travis.yml, packages/validator/test/cli-validator/tests/expected-output.test.js
We no longer support v14 for this tool.
=> fix: use node v18 for travis deployment

CHANGELOG.md, packages/ruleset/CHANGELOG.md, packages/utilities/CHANGELOG.md, packages/validator/CHANGELOG.md
TIL that the root changelog hasn't been updated since we switched to a monorepo, so I updated it to point to the individual changelogs. I also cleaned those up, as there were a few extraneous lines from the 1.0 release.
=> docs: clean up individual changelogs

package-lock.json, packages/validator/src/cli-validator/index.js
This commit modifies the validator's startup script (packages/validator/src/cli-validator/index.js) so that it requires node 16 as the minimum version of the runtime. We had previously updated the package.json to cover the install-related steps.
=> fix: bump minimum node version to 16

package-lock.json, packages/ruleset/package.json, packages/utilities/package.json, packages/validator/package.json
This PR bumps our spectral-related dependencies to their current most recent versions in order to pull in the fix for https://github.ibm.com/arf/planning-sdk-squad/issues/3531
=> fix: bump spectral dependencies

packages/utilities/src/collections/index.js
Fixes: https://github.com/IBM/openapi-validator/issues/438
This commit modifies the "responseSchemas" definition in the collections module so that it uses specific HTTP method names to identify operations.
=> fix(collections): use correct http method names in responseSchemas collection

packages/ruleset/src/functions/required-property.js, packages/ruleset/test/required-property-missing.test.js
Fixes: arf/planning-sdk-squad#3592
This commit fixes the ibm-define-required-properties rule to avoid false positives.  Specifically the logic related to composed models was updated to (hopefully) perform a more accurate set of checks on the schemas in the API definition.
=> fix(ibm-define-required-properties): avoid false positives

README.md, package-lock.json, package.json
There is a community-supported Docker image for running this tool. It is not known to be compromised in any way but it is against our security policies to link to an image controlled by an external agent, so this commit removes the section of the README linking to the external image.
We will likely look into hosting our own image in the future.
This also adds an NPM script for formatting the README's table of contents. The README previously instructed the user to run an NPM package; this way, they don't have to install anything.
=> docs: remove link to external docker image

packages/ruleset/src/functions/unique-parameter-request-property-names.js, packages/ruleset/test/unique-parameter-request-property-names.test.js
Tweaks the validation rule so that it avoids doing checks on readOnly properties since those would not be included in the set of exploded body vars.
=> fix(ibm-unique-parameter-request-property-names): avoid checks on readOnly requestBody properties

package-lock.json, package.json, packages/ruleset/src/functions/array-responses.js, packages/ruleset/src/functions/pagination-style.js, packages/ruleset/src/functions/schema-type-exists.js, packages/ruleset/src/functions/schema-type-format.js, packages/ruleset/test/schema-type-format.test.js, packages/ruleset/test/schema-type.test.js, packages/ruleset/test/string-attributes.test.js, packages/utilities/package.json, packages/utilities/src/utils/get-schema-type.js, packages/utilities/test/get-schema-type.test.js, packages/utilities/test/is-array-schema.test.js, packages/utilities/test/is-object-schema.test.js, packages/utilities/test/schema-is-of-type.test.js
This commit modifies several existing rules along with some ruleset utility functions to allow a schema "type" field to be specified as a list, which is now available in openapi 3.1.
=> fix: support type list in existing rules

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/avoid-multiple-types.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/avoid-multiple-types.js, packages/ruleset/src/rules/index.js, packages/ruleset/test/avoid-multiple-types.test.js
This commit adds a new spectral style rule
"ibm-avoid-multiple-types".  This rule will warn about
any schema that defines multiple non-null type values
in its "type" field.
=> feat(ibm-avoid-multiple-types): add new openapi 3.1 rule

.secrets.baseline, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/pagination-style.js, packages/ruleset/src/functions/prefer-token-pagination.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/prefer-token-pagination.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/pagination-utils.js, packages/ruleset/test/pagination-style.test.js, packages/ruleset/test/prefer-token-pagination.test.js, packages/ruleset/test/ref-sibling-duplicate-description.test.js, packages/ruleset/test/required-property-missing.test.js, packages/ruleset/test/utils/helper-artifacts.js, packages/ruleset/test/utils/index.js, packages/ruleset/test/utils/root-document.js, packages/validator/test/cli-validator/mock-files/oas3/clean-with-tabs.yml, packages/validator/test/cli-validator/mock-files/oas3/clean.yml, packages/validator/test/cli-validator/tests/expected-output.test.js
Adds a rule to check paginated list operations for offset/limit style pagination. If found, a warning is given encouraging the user to use token-based pagination instead.
=> feat(new-rule): ibm-prefer-token-pagination

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/pattern-properties.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/pattern-properties.js, packages/ruleset/test/array-attributes.test.js, packages/ruleset/test/inline-schemas.test.js, packages/ruleset/test/pattern-properties.test.js, packages/ruleset/test/string-attributes.test.js, packages/ruleset/test/utils/test-rule.js, packages/utilities/src/utils/get-schema-type.js, packages/utilities/src/utils/validate-nested-schemas.js, packages/utilities/test/is-object-schema.test.js
This commit introduces a new spectral-style rule named "ibm-pattern-properties" which enforces specific restrictions on the use of the "patternProperties" field within a schema.
=> feat(ibm-pattern-properties): add new spectral-style rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/pattern-properties.js, packages/ruleset/src/functions/unevaluated-properties.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/unevaluated-properties.js, packages/ruleset/test/pattern-properties.test.js, packages/ruleset/test/unevaluated-properties.test.js
This commit introduces the new "ibm-unevaluated-properties" spectral-stye rule to the ruleset.  This rule will make sure that "unevaluatedProperties" is not enabled within a schema.
=> feat(ibm-unevaluated-properties): add new spectral-style rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/resource-response-consistency.js, packages/ruleset/src/functions/response-status-codes.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/resource-response-consistency.js, packages/ruleset/src/utils/get-resource-specific-sibling-path.js, packages/ruleset/src/utils/get-response-codes.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/is-create-operation.js, packages/ruleset/src/utils/is-operation-of-type.js, packages/ruleset/test/array-attributes.test.js, packages/ruleset/test/array-of-arrays.test.js, packages/ruleset/test/avoid-multiple-types.test.js, packages/ruleset/test/get-resource-specific-sibling-path.test.js, packages/ruleset/test/get-response-codes.test.js, packages/ruleset/test/is-create-operation.test.js, packages/ruleset/test/is-operation-of-type.test.js, packages/ruleset/test/pattern-properties.test.js, packages/ruleset/test/property-description.test.js, packages/ruleset/test/property-name-collision.test.js, packages/ruleset/test/resource-response-consistency.test.js, packages/ruleset/test/schema-type-format.test.js, packages/ruleset/test/unevaluated-properties.test.js, packages/ruleset/test/utils/root-document.js
Synchronous responses for create-style POST or update (PUT/PATCH) operations on a given resource should return the canonical schema for the resource. As in, the same schema as the "GET" request for the same resource.
=> feat(new-rule): ibm-resource-response-consistency

packages/ruleset/src/functions/array-of-arrays.js, packages/ruleset/src/functions/etag-header-exists.js, packages/validator/src/cli-validator/run-validator.js
The rule function did not account for missing required properties in parameter
objects and as a result, would crash when they were encountered. This commit
adds handling for this edge case, so that the rule will not crash.
Additionally, errors coming from the `nimma` package in Spectral bury the relevant info
and have been notoriously unhelpful for users and developers alike. This
commit updates the logic to parse out the helpful information and display
it in the error logs.
Resolves #616
=> ibm-etag-headers bug fix

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/response-status-codes.js, packages/ruleset/test/array-attributes.test.js, packages/ruleset/test/response-status-codes.test.js
Added the following new rules:
- PUT methods must define a 200, 201, or 202 status code
- PATCH methods must define a 200 or 202 status code
Also, update the check for create operation status codes to allow 204 status codes when the corresponding resource GET operation also returns a 204.
=> feat(response-status-codes): update rule to check for additional handbook guidance

packages/ruleset/src/functions/array-attributes.js, packages/ruleset/src/functions/duplicate-path-parameter.js, packages/ruleset/src/functions/operationid-naming-convention.js, packages/validator/.releaserc
The `lodash` packages supports installing individual modules via NPM but we use enough modules that we install the whole package. However, we were using the import style for individual modules, which didn't break because the path in `node_modules` was still correct but caused warnings in Spectral (when using custom YAML or JSON rulesets) because of the incorrect names.
This resolves those warnings, which are annoying to users.
Resolves #534
=> fix(imports): use correct imports for lodash modules

.gitignore, package-lock.json, packages/ruleset/src/utils/logger-factory.js
This PR makes sure that the validator and all rules use a single global instance of the LoggerFactory.
=> fix: use single logger instance

package.json, packages/ruleset/package.json, packages/utilities/package.json, packages/validator/.releaserc, packages/validator/package.json
The multi-sem-rel package we use merges the individual release configs into the base project's config. I thought that it deep-merged the arrays but it turns out that the validator package's `plugins` field was overriding the whole `plugins` field in the root config and so we were never actually going to release the package (because the NPM plugin would never be called).
This adds the rest of the plugins we call in the base config to the validator config, so things should return to normal.
=> fix(build): run all release steps for validator build

.gitignore, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/delete-body.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-operation-requestbody.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/no-operation-requestbody.js, packages/ruleset/test/array-attributes.test.js, packages/ruleset/test/delete-body.test.js, packages/ruleset/test/no-operation-requestbody.test.js, packages/ruleset/test/utils/test-rule.js
This commit introduces a new spectral-style rule
'ibm-no-operation-requestbody' which will check to make sure that certain operations (delete, get, head, options) do not have a requestBody defined (as recommended by the API Handbook).
=> feat(ibm-no-operation-requestbody): add new spectral rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-nullable-properties.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/no-nullable-properties.js, packages/ruleset/test/no-nullable-properties.test.js, packages/ruleset/test/utils/root-document.js, packages/utilities/src/collections/index.js, packages/utilities/src/utils/validate-nested-schemas.js, packages/utilities/src/utils/validate-subschemas.js
This commit introduces the new spectral-style rule 'ibm-no-nullable-properties', which will warn about the presence of nullable schema properties in schemas other than JSON merge/patch requestBody schemas (where nullable properties are allowed).
=> feat(ibm-no-nullable-properties): add new spectral-style rule

.secrets.baseline, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/resource-response-consistency.js, packages/ruleset/src/functions/response-status-codes.js, packages/ruleset/src/functions/schema-naming-convention.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/schema-naming-convention.js, packages/ruleset/src/utils/get-resource-specific-sibling-path.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/is-create-operation.js, packages/ruleset/src/utils/schema-finding-utils.js, packages/ruleset/test/array-attributes.test.js, packages/ruleset/test/array-of-arrays.test.js, packages/ruleset/test/circular-refs.test.js, packages/ruleset/test/get-resource-specific-sibling-path.test.js, packages/ruleset/test/pattern-properties.test.js, packages/ruleset/test/property-attributes.test.js, packages/ruleset/test/property-description.test.js, packages/ruleset/test/property-name-collision.test.js, packages/ruleset/test/requestbody-name.test.js, packages/ruleset/test/schema-naming-convention.test.js, packages/ruleset/test/schema-type-format.test.js, packages/ruleset/test/unevaluated-properties.test.js, packages/ruleset/test/unique-parameter-request-property-names.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/test/cli-validator/mock-files/oas3/clean-with-tabs.yml, packages/validator/test/cli-validator/mock-files/oas3/clean.yml, packages/validator/test/cli-validator/mock-files/oas31/clean.yml
Adds a new rule that enforces the schema naming guidelines in the API Handbook.
Specifically, the new rule checks for correctly named collection schemas, resource collection element schemas, creation/replacement schemas, and patch schemas against the name of the associated canonical schema.
=> feat(new-rule): ibm-schema-naming-convention

.secrets.baseline, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/schema-casing-convention.js, packages/ruleset/src/functions/schema-naming-convention.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/schema-casing-convention.js, packages/ruleset/test/schema-casing-convention.test.js
This adds a new rule to verify that schema names (i.e. the keys in the 'schemas' object in the 'components' object) are upper camel case, as specified in the API Handbook.
=> feat(new-rule): ibm-schema-casing-convention

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-ambiguous-paths.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/no-ambiguous-paths.js, packages/ruleset/test/binary-schemas.test.js, packages/ruleset/test/no-ambiguous-paths.test.js, packages/ruleset/test/utils/root-document.js
This commit introduces the new spectral-style rule 'ibm-no-ambiguous-paths' which will check to make sure there are not ambiguous paths defined in the OpenAPI document.
=> feat(ibm-no-ambiguous-paths): introduce new validator rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-unsupported-keywords.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/no-unsupported-keywords.js, packages/ruleset/test/no-unsupported-keywords.test.js
This commit introduces the new 'ibm-no-unsupported-keywords' validation rule which checks to make sure that the (currently) unsupported keywords 'jsonSchemaDialect' and 'webhooks' are not present in an OpenAPI 3.1 document.
=> feat(ibm-no-unsupported-keywords): add new validation rule

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/allowed-keywords.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-operation-requestbody.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/schema-keywords.js, packages/ruleset/test/no-nullable-properties.test.js, packages/ruleset/test/schema-keywords.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/test/cli-validator/mock-files/oas3/err-and-warn.yaml, packages/validator/test/cli-validator/mock-files/oas31/err-and-warn.yaml, packages/validator/test/cli-validator/tests/expected-output.test.js
This commit introduces the new 'ibm-schema-keywords' validation rule which will verify that each schema and schema property are defined with only "allowed" keywords (fields), whwere the set of allowable keywords are defined in a configurable allow list.
=> feat(ibm-schema-keywords): add new validation rule

packages/ruleset/src/ibm-oas.js, packages/validator/test/cli-validator/mock-files/oas3/err-and-warn.yaml, packages/validator/test/cli-validator/mock-files/oas31/err-and-warn.yaml, packages/validator/test/cli-validator/tests/expected-output.test.js, packages/validator/test/cli-validator/tests/option-handling.test.js
This commit modifies the 'no-$ref-siblings' rule which is inherited from Spectral's oas ruleset.  Specifically, we modify the rule so that it is run on OpenAPI 3.1.x documents instead of only 3.0.x documents.
=> feat(no-$ref-siblings): modify rule to also run on OpenAPI 3.1.x documents

packages/ruleset/src/functions/schema-naming-convention.js, packages/ruleset/test/schema-naming-convention.test.js
The Handbook states:
"There is an important exception to this guidance if the nature of an API is to provide clients with full control over entire resources, with no system-defined or immutable aspects. For such APIs, the canonical schema itself SHOULD be used in requests to create or replace a resource."
This commit allows for the name of the canonical schema to be used for resource-oriented POSTs and PUTs.
=> fix(ibm-schema-naming-convention): allow canonical schema for create/replace

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/schema-casing-convention.js, packages/ruleset/src/rules/schema-casing-convention.js, packages/ruleset/test/schema-casing-convention.test.js
It is a common convention to allow capitalized acronyms in schema names, like `IAMCredentialsSecret`. Spectral's `casing` function does not provide us with the flexibility to support this outright, so this PR adjusts the schema casing convention check to use a regular expression instead (the one used in the old, pre-Spectral validator).
=> fix(ibm-schema-casing-convention): allow capitalized acronyms

packages/ruleset/src/functions/api-symmetry.js, packages/ruleset/test/api-symmetry.test.js
If reference schemas were nested in composed properties on the canonical schema, the code would not resolve them the way it would for non-nested reference schemas.
This moves the resolving code to the constraint checker, so that every schema and applicator sub-schema will be resolved if it is a reference.
=> fix(api-symmetry): handle nested reference schemas

package-lock.json, packages/validator/package.json, packages/validator/src/cli-validator/run-validator.js, packages/validator/src/cli-validator/utils/check-ruleset-version.js, packages/validator/src/cli-validator/utils/cli-options.js, packages/validator/src/cli-validator/utils/get-default-ruleset-version.js, packages/validator/src/cli-validator/utils/get-local-ruleset-version.js, packages/validator/src/cli-validator/utils/get-version-string.js, packages/validator/src/cli-validator/utils/print-versions.js, packages/validator/src/spectral/spectral-validator.js, packages/validator/src/spectral/utils.js, packages/validator/test/cli-validator/tests/configuration-manager.test.js, packages/validator/test/cli-validator/tests/option-handling.test.js
Before this commit, the --version option would print the version of the validator tool and the version of the IBM Cloud OpenAPI Ruleset that is run by default if the user doesn't provide their own ruleset.
However, if the user did use their own, locally installed version of our ruleset, the version included in the output of the tool would not actually reflect the version being used. Additionally, users could install new versions of the validator tool but if they didn't update their locally installed instance of the ruleset, they would not get the updated behavior of the rules (which are often the reasons for bumping the version of the tool).
This commit adds logic to print the actually used (whether the default or locally installed) ruleset version and additionally will print a warning if …
=> feat: display actual ruleset version with --version option

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/well-defined-dictionaries.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/well-defined-dictionaries.js, packages/ruleset/test/well-defined-dictionaries.test.js
Adds a rule to ensure that dictionary types are well defined, meaning:
- All values in the dictionary must conform to a single type
- Schemas are not hybrid model-dictionaries (defining both properties and additional properties)
=> feat(new-rule): ibm-well-defined-dictionaries

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/resource-response-consistency.js, packages/ruleset/test/resource-response-consistency.test.js
This commit adds support for recognizing bulk operations and recommending the collection schema be returned instead of the canonical schema. It also:
- Updates the message to be more clear
- Updates the path to be more aligned with the operation
- Adds an "info" log pointing to the specific operation in case it is unclear
Previously, the rule would flag a bulk operation that didn't return the collection schema but it did so unintentionally (and with a bad heuristic) and the message would indicate that the canonical schema should be returned, which was false (often, the canonical schema *was* being returned).
Also, the warning would be tied to a specific schema and it was difficult to parse the debug logs to determine which operation was responsible for the warning.
Please make sure that …
=> fix(ibm-resource-response-consistency): expand support to bulk operations

packages/ruleset/src/functions/resource-response-consistency.js, packages/validator/src/cli-validator/utils/get-copyright-string.js
Addresses a bug reported in which a property is attempted to be deconstructed from an object type. When the `getCanonicalSchema` function was converted to return an object, a return statement was left unconverted and was still returning undefined. This caused the bug upon attempted deconstruction of the return value.
Also, I updated the project copyright string for the new year.
=> fix(resource-response-consistency): avoid destructuring property of undefined values

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/parameter-casing-convention.js, packages/ruleset/src/rules/parameter-casing-convention.js, packages/ruleset/test/parameter-casing-convention.test.js, packages/utilities/src/collections/index.js
This allows us to support standard header patterns that would previously be flagged by the validator. The `casing` function options provided by Spectral are not sophsiticated enough to support the complexity of header parameter conventions (which use kebab-separated pascal case with capitalized abbreviations).
The new regular expression is a little more relaxed than the old convention but it also more accurate.
I made this change in a configuration-compatible way by expanding the config support to accept function arguments for either the casing or pattern built-in Spectral functions. This is slightly hacky but gives both us and users more control without changing any existing behavior. We might want to make this change for our other casing convention checks but for now, this is sufficient …
=> fix: adjust header parameter casing convention check

.releaserc, packages/ruleset/src/functions/check-major-version.js, packages/validator/.releaserc
This commit modifies the semantic-release configuration (.releaserc) slightly to make sure we build the executables after we have published the validator package.
The intent is to make sure that the executables are built with the correct version of the ruleset and ruleset-utilities packages.
Edit: I made a small change to the ibm-major-version-in-path rule's function to add a debug message simply to have an easy way to verify that the latest version of the ruleset is being packaged with the executable that is produced.   I can remove this change while working on the next validator issue.
=> fix(build): build binaries after npm package has been published

.secrets.baseline, package-lock.json, packages/ruleset/package.json, packages/utilities/package.json, packages/validator/.releaserc, packages/validator/package.json, scripts/create-binaries.sh
This commit modifies the create-binaries.sh script so that it removes the packages/validator/node_moduels/@ibm-cloud directory prior to invoking pkg to build the executables.
This fixes a problem where the executables would end up with the "old" version of the openapi-ruleset dependency in situations where we're also publishing a new version of that dependency. Removing the dependency from packages/validator/node_modules means that pkg would end up using the dependencies in the project's top-level "node_modules" directory instead, which will have the correct version of the dependency.
=> fix(build): build executables with correct dependency versions

packages/ruleset/src/functions/check-major-version.js
This PR removes a debug message that was recently added to the check-major-version.js file in order to verify that the executables are being built correctly.
Removing this debug message will trigger a new version of the ruleset dependency and will allow us to verify that things are working correctly with the new fix that we have in place for the "pkg" problem.
=> fix(ibm-major-version-in-path): remove extraneous debug message

packages/ruleset/src/functions/request-and-response-content.js, packages/ruleset/src/functions/response-status-codes.js, packages/ruleset/src/utils/path-has-minimally-represented-resource.js, packages/ruleset/test/response-status-codes.test.js
This commit modifies the ibm-response-status-codes rule so that a PUT that returns a 204 status code will be allowed if there is a corresponding GET operation on the same path that also returns a 204.
=> fix(ibm-response-status-codes): allow PUT w/204 if a GET w/204 exists

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/operation-summary-length.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/operation-summary-length.js, packages/ruleset/test/operation-summary-exists.test.js, packages/ruleset/test/operation-summary-length.test.js
Adds a rule that verifies operation summaries are 80 characters or less in length, based on the summary writing guidance in the API Handbook.
A question for the PR reviewers. We already have these existing rules:
- ibm-operation-summary (checks that a summary exists on every operation)
- ibm-summary-sentence-style (checks that a summary does not end with a period)
Should this check be merged into one of the existing rules or does it belong as its own rule? The granularity is nice for configuration but it might be confusing to have too many rules doing such similar things. What do y'all think?
=> feat(new-rule): ibm-operation-summary-length

.travis.yml, packages/validator/test/cli-validator/tests/configuration-manager.test.js, packages/validator/test/cli-validator/tests/error-handling.test.js
Version 20 of Node changes the behavior of error messages. Where the
tests relied on equality with specific error messages, they have been
updated to match against slightly more generic regular expressions to
support running the tests.
Also, v20 is added to the Travis builds as it is the current LTS version.
Resolves #662
=> Modify tests to work with Node v20

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-superfluous-allof.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/no-superfluous-allof.js, packages/ruleset/test/no-superfluous-allof.test.js
This commit adds the new "ibm-no-superfluous-allof" rule which warns about the use of a superfluous allOf, which is a schema that contains only a single-element allOf.
=> feat(ibm-no-superfluous-allof): add new rule and documentation

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-ref-in-example.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/no-ref-in-example.js, packages/ruleset/test/no-ref-in-example.test.js
This commit introduces the new 'ibm-no-ref-in-example' rule which will check to make sure that "$ref" is not used in "example" fields.  Note that $ref is valid in an "examples" field, but not in an "example" field.
=> feat: add new 'ibm-no-ref-in-example' rule

.secrets.baseline, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/array-attributes.js, packages/ruleset/src/functions/property-attributes.js, packages/ruleset/src/functions/string-attributes.js, packages/ruleset/src/rules/string-attributes.js, packages/ruleset/test/array-attributes.test.js, packages/ruleset/test/property-attributes.test.js, packages/ruleset/test/string-attributes.test.js
Issues fixed:
- Not all of the keywords were considered invalid for non-scoped schemas
- min/max comparison didn't take 0 as a falsy value into account
- Only input schemas were considered for keyword checks on non-strings
Please make sure that your PR fulfills the following requirements:  
N/A
=> fix(*-attributes): fill gaps in (array|property|string)-attributes rules

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/requestbody-name.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/requestbody-name.js, packages/ruleset/test/requestbody-name.test.js
Now that the IBM API Handbook provides [firm and robust guidance](https://cloud.ibm.com/docs/api-handbook?topic=api-handbook-schemas#naming) on schema naming and we validate for this guidance in 'ibm-schema-naming-convention', requiring the 'x-codegen-request-body-name' to be specified on relevant schemas is no longer necessary. It is resulting in APIs having to duplicate names between the schema name, title, and extension. This rule will remain in place for teams that wish to use it but this commit turns it off by default.
=> fix(ibm-requestbody-name): turn rule off by default, is now redundant

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/pattern-properties.js, packages/ruleset/test/pattern-properties.test.js
This commit adds an additional check to the rule dealing with `pattern-properties`. It requires the use of starting and ending anchors (^ and $, respectively) for the regular expression it defines as its single element, much like we require for the `pattern` field of string schemas.
=> feat(ibm-pattern-properties): enforce use of anchors for property patterns

packages/ruleset/src/functions/accept-and-return-models.js, packages/ruleset/test/accept-and-return-models.test.js, packages/validator/test/cli-validator/tests/expected-output.test.js, packages/validator/test/cli-validator/tests/option-handling.test.js
When checking that request/response bodies are defined as models, we don't need to check schemas that aren't objects. These schemas should be objects, but there are other rules that will catch that and it's confusing for the validator to tell users they need the "properties" field on a non-object schema.
=> fix(ibm-accept-and-return-models): exempt non-object schemas

docs/ibm-cloud-rules.md, packages/ruleset/src/functions/string-attributes.js, packages/ruleset/test/string-attributes.test.js, packages/ruleset/test/utils/root-document.js, packages/validator/test/cli-validator/mock-files/oas3/clean-with-tabs.yml, packages/validator/test/cli-validator/mock-files/oas3/clean.yml, packages/validator/test/cli-validator/mock-files/oas31/clean.yml
The rule only applied to "input" schemas, which are more important to check for the attributes, but the API Handbook recommends the attributes for repsonse schemas as well. This commit expands the rule to check for those scenarios.
=> fix(ibm-string-attributes): expand rule to apply to response schemas

packages/ruleset/src/utils/get-schema-name-at-path.js
Before, the check used faulty logic to determine if we were on the last iteration through a loop. This could lead to unintended behavior in rare cases. This clarifies the logic to only execute the last time through the loop and for no other reason (the potential reason being if the last path segment matched an earlier path segment).
=> fix: make schema path de-resolution utility more robust

package-lock.json, package.json, packages/ruleset/package.json, packages/utilities/package.json, packages/validator/package.json
Updates the spectral dependencies to address CVE-2024-21534.
<s>There was a single test failure, it seems spectral returns a bit more information around where the error happens, have updated the test to reflect that.</s>
=> chore: update spectral dependencies, addresses CVE-2024-21534

.secrets.baseline, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/api-symmetry.js, packages/ruleset/src/functions/well-defined-dictionaries.js, packages/ruleset/test/rules/well-defined-dictionaries.test.js, packages/utilities/src/utils/index.js, packages/utilities/src/utils/schema-loosely-has-constraint.js, packages/utilities/test/schema-loosely-has-constraint.test.js
Two changes:
The API Handbook states that the values for dictionaries should not themselves
be dictionaries (no dictionaries of dictionaries). Previously, this rule would
not catch that scenario. Now, it will.
Additionally, more robust logic is used to check for the presence of ambiguous
dictionaries. The old logic would miss flagging valid violations in complex,
composed schemas without the fix.
The existing `schemaHasConstraint` function will only determine a schema meets
the given constraint when every element of a `oneOf` or `anyOf` list. This is
desired behavior in the majority of cases. However, in some cases, it is
helpful to note when a schema includes a `oneOf` or `anyOf` list with only a
single element meeting the constraint, instead of all of them. The new utility
function, …
=> check for schemas that are dictionaries of dictionaries

.github/pull_request_template.md, .secrets.baseline, packages/ruleset/src/functions/binary-schemas.js, packages/ruleset/src/functions/property-description-exists.js, packages/ruleset/src/functions/schema-description-exists.js, packages/ruleset/src/utils/index.js, packages/ruleset/src/utils/path-location-utils.js, packages/ruleset/test/utils/path-location-utils.test.js
A couple of the regular expressions we use for determining the location of a given OpenAPI artifact based on the path had minor bugs that would prevent expected operations for edge cases. These are now resolved. Also, they are now packaged into utilities for easy sharing between rules and increased readability within the rule function code itself.
=> fix: adjust path location regular expressions to handle edge cases

README.md, packages/utilities/README.md, packages/validator/README.md
Things like the newest CLI options, the new utility package docs, and the AQS docs were not included or linked to from the relevant readme files. This commit catches them up to date.
=> docs: update all package readmes with latest changes

docs/openapi-ruleset-utilities.md, packages/utilities/src/utils/collect-from-composed-schemas.js, packages/utilities/src/utils/get-examples-for-schema.js, packages/utilities/src/utils/get-property-names-for-schema.js, packages/utilities/src/utils/index.js, packages/utilities/test/collect-from-composed-schemas.test.js, packages/utilities/test/get-examples-for-schema.test.js
Adds a generic `collectFromComposedSchemas()` function that can be used to build functions like the also-added `getExamplesForSchema()`, and refactors `getPropertyNamesForSchema()` to use `collectFromComposedSchemas()` as well.
=> feat: add `collectFromComposedSchemas()` and `getExamplesForSchema()` to utilities

docs/openapi-ruleset-utilities.md, packages/utilities/src/utils/schema-path.js, packages/utilities/src/utils/validate-composed-schemas.js, packages/utilities/src/utils/validate-nested-schemas.js, packages/utilities/src/utils/validate-subschemas.js, packages/utilities/test/schema-path.test.js, packages/utilities/test/validate-composed-schemas.test.js, packages/utilities/test/validate-nested-schemas.test.js, packages/utilities/test/validate-subschemas.test.js
=> feat: track logical paths in recursive validation functions

.secrets.baseline, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/collection-array-property.js, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/no-ambiguous-paths.js, packages/ruleset/src/functions/use-date-based-format.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/use-date-based-format.js, packages/ruleset/src/utils/date-based-utils.js, packages/ruleset/src/utils/index.js, packages/ruleset/test/rules/required-enum-properties-in-response.test.js, packages/ruleset/test/rules/use-date-based-format.test.js, packages/ruleset/test/utils/date-based-utils.test.js, packages/ruleset/test/utils/is-operation-of-type.test.js, packages/validator/src/scoring-tool/rubric.js
This commit introduces the new 'ibm-use-date-based-format' rule,
which will heuristically verify that schemas, with either a name
or an example value indicating a date-based logical type, be
strings and use either "date" or "date-time" as the format.
=> feat(ibm-use-date-based-format): introduce new validation rule

.github/workflows/build.yaml, .github/workflows/docker.yaml, README.md, packages/validator/.releaserc, scripts/deploy-container-image.sh
This offers greater control to retry the Docker deployment step in the event that it fails, independently of the release being published. We've observed the network request being fragile during builds, so it is important to be able to retry this step without re-running the release publishing step.
This commit also removes the Travis badge from the README and aligns the naming and formatting in the build workflow with our other projects.
=> build: separate docker deployment into tagged release build

.secrets.baseline, docs/ibm-cloud-rules.md, packages/ruleset/src/functions/well-defined-dictionaries.js, packages/ruleset/test/rules/well-defined-dictionaries.test.js
Currently, the rule only considers dictionaries defined with `additionalProperties`. OpenAPI 3.1.x supports defining dictionaries with `patternProperties`, so this commit adds consideration for this field in its validation, in addition to `additionalProperties`.
=> fix(ibm-well-defined-dictionaries): include patternProperties in validation

packages/ruleset/src/functions/api-symmetry.js, packages/ruleset/test/rules/api-symmetry.test.js
This rule was subject to both false positives, as it flagged any schema with a
dictionary property (even when inappropriate), and false negatives, as it did
not check top-level schemas, only schema properties. This fix resolves both
issues and cleans up the rule logic on the whole.
Additionally, changes are made to the rule's logging. The code
to determine if one schema is a graph fragment of the other
uses a depth-first algorithm that prints a log, if it determines the
schema to violate the graph fragment pattern, with the reason behind
the violation. Due to the depth-first nature of the algorithm, the
logs are currently printed in depth first order, which is not as
coherent for the user to read.
This change introduces a stack to collect the logs during processing
and print them in …
=> fix(ibm-api-symmetry): handle dictionaries and top-level schemas

packages/ruleset/src/utils/date-based-utils.js, packages/ruleset/test/utils/date-based-utils.test.js
The regular expressions used to determine if a value should be considered a date-time value are too loose and allow false positives to sneak in. It's a tricky problem, but this commit makes an attempt to tighten them by dismissing the possibility of a date-time value if any letters are found that are not relevant to a date-time value.
=> fix(ibm-use-date-based-format): tighten heuristic for flagging date-time values

packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/typed-enum.js, packages/ruleset/test/rules/typed-enum.test.js
This Spectral rule checks any object that has a type and enum field, regardless of whether it is in a valid schema location or not. This fix modifies the given paths to run the same functionality against schema objects only.
This will resolve a number of recently observed false positives.
=> fix(typed-enum): modify spectral rule to look only at schemas

docs/automated-quality-screening.md
I apparently couldn't be consistent myself, so I think whatever semantic benefit I would argue for "qualitative", it cannot overcome the friction.
=> Purge "qualitative" for consistency

packages/ruleset/src/utils/date-based-utils.js, packages/ruleset/test/utils/date-based-utils.test.js
This adjustment to the date-based value heuristic prevents a time from being detected if the word boundary is a colon character. This prevents colon-separated values that might otherwise look like dates, like MAC addresses, from being detected.
=> fix(ibm-use-date-based-format): avoid false positives for mac addresses

packages/ruleset/src/functions/use-date-based-format.js, packages/ruleset/test/rules/use-date-based-format.test.js
Previously, if the example value given for a property was an explicit 'null', this rule would crash the validator.
This commit filters null examples from the logic so that they won't cause any trouble.
=> fix(ibm-use-date-based-format): handle null example values

docs/ibm-cloud-rules.md, package-lock.json, packages/ruleset/package.json, packages/ruleset/src/functions/index.js, packages/ruleset/src/functions/use-date-based-format.js, packages/ruleset/src/functions/valid-schema-example.js, packages/ruleset/src/ibm-oas.js, packages/ruleset/src/rules/index.js, packages/ruleset/src/rules/valid-schema-example.js, packages/ruleset/src/utils/date-based-utils.js, packages/ruleset/test/rules/use-date-based-format.test.js, packages/ruleset/test/rules/valid-schema-example.test.js, packages/ruleset/test/utils/date-based-utils.test.js, packages/validator/src/scoring-tool/rubric.js
Introduce a new rule for confirming that schema examples are valid instances of the schemas they are defined on.
This replaces the Spectral rule 'oas3-valid-schema-example', which has reported a number of false positives across IBM APIs.
=> feat(ibm-valid-schema-example): introduce new validation rule

.releaserc, scripts/create-binaries.sh
This commit fixes the create-binaries.sh script
by adding the "-t" (targets) option to explicitly
specify the node versions for which the executables should be built.
Because we haven't successfully published the executables in about 9 months (!), I also modified the semantic-release configuration so that we avoid the steps to build and publish the executables.  If we need to add this back later, it should be relatively easy since the create-binaries.sh script is now fixed.
=> build: fix exe build script

.secrets.baseline, package-lock.json, package.json, packages/ruleset/package.json, packages/utilities/package.json, packages/validator/package.json
Bumps our version of jsonpath-plus to avoid a CVE
=> build: bump jsonpath-plus to avoid CVE

packages/ruleset/src/functions/api-symmetry.js, packages/ruleset/test/rules/api-symmetry.test.js
Previously, if a canonical schema contained a reference to its corresponding reference schema, it would create an infinite cycle when the rule tried to resolve a reference schema into its corresponding canonical schema.
This commit adds logic to detect that scenario and prevent the cycle.
=> fix(ibm-api-symmetry): handle dependencies between canonical and reference schemas

packages/utilities/src/collections/index.js, packages/utilities/test/collections.test.js, packages/utilities/test/utils/test-rule-paths.js, packages/utilities/test/utils/test-rule.js, packages/utilities/test/validate-subschemas.test.js
- Rename `responseSchemas` to `responseBodySchemas` (matching `requestBodySchemas`) since there are also response _header_ schemas considered separately.
- Add response header **content** schemas to consideration in the `schemas` collection (they were already considered in the `unresolvedSchemas` collection) and rework the schema collection slightly for clarity.
- Add tests for all collections!
- ~[ ] Dependencies have been updated as needed~
- ~[ ] `.secrets.baseline` has been updated as needed~
- ~[ ] Added new validation rule definition (packages/ruleset/src/rules/*.js, index.js)~
- ~[ ] If necessary, added new validation rule implementation~(packages/ruleset/src/functions/*.js, updated index.js)~
- ~[ ] Added new rule …
=> Fix minor problems with utility collections and add tests
